src/analyzer/analyzer.py
Not handling it causes analyzer to crash.
=> Handle connection error to Graphite

docs/overview.rst
I think this page could use additional work.  Some of the ways you described the way pieces work together in an email to me were much better i think.
=> Couple typos / deleted fluff

docs/running-in-python-virtualenv.rst
Updated two things which may not be universal... I'm not a python developer so you may want to verify.
Followed this link for the :amd64 addition
=> Update path to python binary

.gitignore
added data/* and check/* for good measure.
=> Ignore crucible files

docs/_build/html/_modules/ionosphere/layers.html, docs/_build/html/_sources/monotonic-metrics.txt, docs/_build/html/monotonic-metrics.html, docs/analyzer.rst, docs/getting-started.rst, docs/installation.rst, docs/ionosphere.rst, docs/mirage.rst, docs/monotonic-metrics.rst, skyline/analyzer/alerters.py, skyline/analyzer/analyzer.py, skyline/ionosphere/ionosphere.py, skyline/ionosphere/learn.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py, skyline/settings.py, skyline/skyline_functions.py, skyline/webapp/ionosphere_backend.py, skyline/webapp/templates/search_features_profiles.html, skyline/webapp/webapp.py
Merging analyse_derivatives, rate limiting profile learning and layers docs.
=> Ionosphere

docs-requirements.txt, docs/_build/html/mirage-1.py, docs/development/building-documentation.rst, docs/installation.rst, skyline/analyzer/alerters.py, skyline/analyzer_dev/alerters.py, skyline/boundary/boundary.py, skyline/boundary/boundary_alerters.py, skyline/crucible/crucible.py, skyline/features_profile.py, skyline/horizon/listen.py, skyline/ionosphere/ionosphere.py, skyline/ionosphere/learn.py, skyline/ionosphere_functions.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py, skyline/mirage/negaters.py, skyline/panorama/panorama.py, skyline/skyline_functions.py, skyline/webapp/backend.py, skyline/webapp/ionosphere_backend.py, skyline/webapp/templates/features_profiles.html, skyline/webapp/templates/ionosphere.html, skyline/webapp/templates/search_features_profiles.html, skyline/webapp/webapp.py, tests/baseline/tsfresh_features_test.py, utils/numpy_vs_msgpack.py, utils/seed_data.py
Adding the functions and html for a Matches page
=> Ionosphere - matches page

skyline/ionosphere_functions.py
=> Deprecate mysql_key_block_size

readthedocs.yml
Added as readthedocs in broken as per https://github.com/rtfd/readthedocs.org/pull/4379
Added:
readthedocs.yml
=> readthedocs.yml

docs/readthedocs.requirements.txt, skyline/ionosphere/ionosphere.py
IssueID #2448: luminosity-1.2.2-stable
readthedocs issue? testing updating pip
Modified:
docs/readthedocs.requirements.txt
=> v1.2.2-luminosity

docs/ionosphere.rst
IssueID #2430: Ionosphere validate learnt features profiles page (#68)
- Added validate_features_profile_demo_page
Modified:
=> #68 Ionosphere validate learnt features profiles page

docs/overview.rst, docs/releases/1_2_5.rst
IssueID #2486: v1.2.5-stable-luminosity
- Documentation changes for v1.2.5-stable-luminosity
Added:
Modified:
docs/releases/1_2_5.rst
docs/overview.rst
=> docs and version update for v1.2.5-stable-luminosity

docs/releases/1_2_6.rst
IssueID #2546: Fix SQL errors
- Documentation fix for v1.2.6-stable-luminosity
Modified:
docs/releases/1_2_6.rst
=> fix docs for v1.2.6 upgrade

docs/releases/1_2_16.rst
Modified:
docs/releases/1_2_16.rst
=> update deps - correct path

dev-requirements.txt, docs/readthedocs.requirements.txt, docs/releases/1_2_16.rst, requirements.txt
Modified:
docs/readthedocs.requirements.txt
docs/releases/1_2_16.rst
=> urllib3 fix to 1.24.3

skyline/analyzer/alerters.py, skyline/boundary/boundary_alerters.py, skyline/mirage/mirage_alerters.py
IssueID #3290: Handle urllib2 in py3
IssueID #3294: py3 - handle system parameter in Graphite cactiStyle
Modified:
=> py3 alerter changes

skyline/skyline_functions.py
IssueID #3290: Handle urllib2 in py3
IssueID #3304: py3 - handle pymemcache bytes not str
Modified:
=> py3 skyline_function changes

skyline/boundary/boundary.py, skyline/boundary/boundary_algorithms.py
Modified:
skyline/boundary/boundary_algorithms.py
=> py3 boundary changes

skyline/horizon/roomba.py
Modified:
skyline/horizon/roomba.py
=> py3 horizon roomba changes

skyline/luminosity/luminosity.py, skyline/luminosity/process_correlations.py
IssueID #3304: py3 - handle pymemcache bytes not str
Modified:
skyline/luminosity/luminosity.py
=> py3 luminosity changes

skyline/mirage/mirage.py
=> py3 mirage changes

skyline/panorama/panorama.py
=> py3 panorama changes

skyline/webapp/ionosphere_backend.py, skyline/webapp/webapp.py
IssueID #3302: Handle csv.reader in py3
IssueID #3304: py3 - handle pymemcache bytes not str
Modified:
=> py3 webapp changes

docs/docker.rst, docs/ionosphere.rst, skyline/docker.settings.py.default, utils/dawn/skyline.dawn.sh, utils/verify_alerts.py
- Added ability to install Graphite on docker CentOS 6 and Ubuntu 16.04
- Misc documentation
Modified:
docs/docker.rst
skyline/docker.settings.py.default
utils/verify_alerts.py
=> py3 misc changes

skyline/skyline.sql, updates/sql/v2.0.0.sql
Added:
updates/sql/v2.0.0.sql
Modified:
=> py3 SQL changes

skyline/panorama/panorama.py, skyline/webapp/backend.py, skyline/webapp/static/js/panorama.js, skyline/webapp/templates/panorama.html
- In Panorama UI
Modified:
skyline/webapp/static/js/panorama.js
skyline/webapp/templates/panorama.html
=> Record anomaly_end_timestamp

skyline/flux/populate_metric_worker.py
IssueID #3312: flux - populate_metric_worker - handle None in datapoints
Modified:
=> flux - populate_metric_worker - handle None in datapoints

skyline/mirage/mirage.py
- Use get_redis_conn functions
- urlparse
Modified:
=> py3 mirage

skyline/ionosphere/agent.py, skyline/ionosphere/common_functions.py, skyline/ionosphere/ionosphere.py, skyline/ionosphere/layers.py, skyline/ionosphere/learn.py
Modified:
skyline/ionosphere/agent.py
skyline/ionosphere/common_functions.py
skyline/ionosphere/layers.py
=> ionosphere py3 changes

skyline/panorama/agent.py, skyline/skyline_functions.py, skyline/skyline_version.py, skyline/tsfresh_features/autobuild_features_profile_tables.py, skyline/tsfresh_features/scripts/make-pytz.all_timezones-rst.py, skyline/vista/agent.py
Modified:
skyline/panorama/agent.py
skyline/skyline_version.py
skyline/tsfresh_features/autobuild_features_profile_tables.py
skyline/tsfresh_features/scripts/make-pytz.all_timezones-rst.py
skyline/vista/agent.py
=> misc flake8 py3 changes

skyline/settings.py, skyline/vista/fetcher.py
IssueID #3338: Vista - batch Graphite requests
- Vista - batch Graphite requests
Modified:
skyline/vista/fetcher.py
=> Vista - batch Graphite requests#

skyline/webapp/webapp.py
IssueID #3336: webapp api - derivative_metrics
- Added derivative_metrics api method
Modified:
=> webapp api - derivative_metrics

skyline/webapp/webapp.py
IssueID #3348: fp creation json response
IssueID #3350: webapp api - mirage_metrics and ionosphere_metrics
- Add webapp api methods for mirage_metrics and ionosphere_metrics
- Added json response for fp creation if the format=json parameter is passed
Modified:
=> webapp more api methods

.gitignore, skyline/flux/flux.py, skyline/skyline.sql, skyline/vista/fetcher.py, skyline/webapp/webapp.py, updates/sql/v2.0.0.sql
IssueID #3368: webapp api - ionosphere_learn_work
IssueID #3230: users DB table
IssueID #3370: Add additional indices to DB
- Added .idea to gitignore for pycharm
- flake8 changes
- Added ionosphere_learn_work webapp api method
- Allow the user_id to be passed as a ionosphere request argument
- Add additional indices to DB
Modified:
.gitignore
skyline/vista/fetcher.py
updates/sql/v2.0.0.sql
=> py3 various changes

skyline/ionosphere/ionosphere.py, skyline/ionosphere_functions.py, skyline/webapp/webapp.py
IssueID #3380: Create echo features profile when a Mirage features profile is created
- Create echo features profile when a Mirage features profile is created
Modified:
=> Create echo features profile when a Mirage features profile is created

skyline/ionosphere/learn.py
IssueID #3382: Prevent ionosphere.learn loop edge cases
- Added work check to ensure that ionosphere.learn does not learn a
learn_full_duration_days features profile over and over until work_age limit
is reached as discovered in a single edge.
Modified:
=> Prevent ionosphere.learn loop edge cases

dev-requirements.txt, requirements.txt, skyline/flux/listen.py, skyline/flux/populate_metric_worker.py, skyline/ionosphere_functions.py, skyline/settings.py, skyline/skyline.sql, skyline/skyline_functions.py, skyline/vista/fetcher.py, skyline/vista/worker.py, skyline/webapp/ionosphere_backend.py, skyline/webapp/templates/correlations.html, skyline/webapp/webapp.py
New features:
- related anomalies and matches
- handle lower frequency in Vista and Flux
=> New features and misc changes

skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py
IssueID #3034: Reduce multiprocessing Manager list usage
- misc py3 related changes and additional exception handliing and debug logging
in mirage.py (3262, 3034)
- Use file not buf.seek in mirage_alerters.py (3262)
Modified:
=> misc py3 changes

skyline/flux/listen.py
IssueID #3394: flux health check
- Added status parameter so that the flux listen process can be monitored
Modified:
=> flux health check

skyline/flux/listen.py, skyline/flux/worker.py
IssueID #3444: Allow flux to backfill
- Added the fill parameter to listen.py to allow flux to fill airgaps in
metrics.
- Added the backfill item to worker.py to allow flux to not check the flux.last
metric Redis key and allow the filling of airgaps in metrics.
Modified:
=> Allow flux to backfill

docs/crucible.rst, skyline/crucible/crucible.py, skyline/crucible/crucible_algorithms.py
IssueID #3290: Handle urllib2 in py3
IssueID #868: crucible
- Use os.chmod py2 and py compatible mode e.g. 0o644
- Wrap later imports up in while True
- Updated crucible doc with py3 example
Modified:
docs/crucible.rst
skyline/crucible/crucible_algorithms.py
=> update crucible to py3

skyline/analyzer/alerters.py, skyline/boundary/boundary_alerters.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py
- Fix Mirage undecoded alert_on cache key
Modified:
=> fix Mirage undecoded alert key

skyline/webapp/ionosphere_backend.py, skyline/webapp/templates/api.html, skyline/webapp/templates/panorama.html, skyline/webapp/webapp.py
IssueID #2476: Label and relate anomalies
IssueID #3474: webapp api - training_data
IssueID #3464: Optimise ionosphere_backend ionosphere_search queries
- Added new label anomalies functionality (#2476)
- Added the webapp api training_data method (#3474)
- Began optimising ionosphere_search queries (#3464)
Added:
skyline/webapp/templates/label_anomalies.html
Modified:
skyline/webapp/templates/panorama.html
=> webapp additions

skyline/vista/worker.py
IssueID #3476: vista - handle very large floats
- Use numpy format_float_positional to handle very large floats so that flux is
never passed a like value=1.00243039089e+11
Modified:
skyline/vista/worker.py
=> vista - handle very large floats

docs/analyzer.rst, docs/boundary.rst, docs/conf.py, docs/docker.rst, docs/index.rst, docs/ionosphere.rst, docs/mirage.rst, docs/overview.rst, docs/slack.rst, docs/upgrading/index.rst, docs/upgrading/py2-to-py3.rst, docs/vista.rst, etc/skyline.conf, skyline/ionosphere_functions.py, skyline/tsfresh_features/autobuild_features_profile_tables.py, skyline/webapp/utilities.py, utils/dawn/skyline.dawn.sh
- py3 docs changes
- Update skyline.dawn.sh to py3
Modified:
docs/boundary.rst
docs/conf.py
docs/docker.rst
docs/index.rst
docs/mirage.rst
docs/overview.rst
docs/slack.rst
docs/upgrading/index.rst
docs/upgrading/py2-to-py3.rst
docs/vista.rst
etc/skyline.conf
skyline/tsfresh_features/autobuild_features_profile_tables.py
skyline/webapp/utilities.py
=> py3 docs changes and misc

docs/alerts.rst, docs/running-in-python-virtualenv-py2.rst, etc/skyline.apache2.conf.d.example
- py3 docs changes and additions
Added:
etc/skyline.apache2.conf.d.example
docs/alerts.rst
docs/running-in-python-virtualenv-py2.rst
docs/upgrading/py2-to-py3.rst
=> py3 docs changes and additions

skyline/webapp/templates/label_anomalies.html
IssueID #2476: Label and relate anomalies
- Added missed new label anomalies file (#2476)
Added:
skyline/webapp/templates/label_anomalies.html
=> Label and relate anomalies

skyline/skyline.sql, updates/sql/v2.0.0.sql
IssueID #3478: sql_versions table
- Missing )
Modified:
updates/sql/v2.0.0.sql
=> sql_versions

skyline/skyline.sql, updates/sql/v2.0.0-patch-3478.sql, updates/sql/v2.0.0.sql
=> v2.0.0-patch-3478

skyline/analyzer/analyzer.py, skyline/analyzer/analyzer_batch.py
- Enable Analyzer to still identify stale metrics in batch metrics and turn off
enable_batch_processing_logging
- Log if now timestamps are found to analyse in analyzer_batch
- In analyzer_batch Handle there being no timestamps_to_analyse and report such
as otherwise the only info logged is that the work key just gets removed.
Modified:
=> analyzer_batch batch_processing

bin/analyzer.d, bin/analyzer_batch.d, bin/analyzer_dev.d, bin/boundary.d, bin/crucible.d, bin/flux.d, bin/horizon.d, bin/ionosphere.d, bin/luminosity.d, bin/mirage.d, bin/panorama.d, bin/skyline.d, bin/vista.d, bin/webapp.d, docs/installation.rst, docs/upgrading/py2-to-py3.rst
IssueID ##3262: py3
- Handle skyline user with no sudo access, do not use sudo
- Update docs/upgrading/py2-to-py3.rst and docs/installation.rst (remove hipchat)
Modified:
bin/analyzer.d
bin/analyzer_batch.d
bin/analyzer_dev.d
bin/boundary.d
bin/crucible.d
bin/flux.d
bin/horizon.d
bin/ionosphere.d
bin/luminosity.d
bin/mirage.d
bin/panorama.d
bin/skyline.d
bin/vista.d
bin/webapp.d
docs/upgrading/py2-to-py3.rst
=> Handle skyline user with no sudo access

skyline/analyzer/analyzer.py
IssueID Feature #3486: analyzer_batch
- Use redis_conn_decode on analyzer_batch keys in analyzer for py3
Modified:
=> redis_conn_decode on analyzer_batch keys in analyzer

skyline/analyzer_dev/alerters.py, skyline/boundary/boundary_alerters.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py, skyline/mirage/negaters.py, skyline/webapp/webapp.py
IssueID #3294: py3 - handle system parameter in Graphite cactiStyle
- Add the si parameter to all contexts where it had not been added.
Modified:
skyline/analyzer_dev/alerters.py
skyline/mirage/negaters.py
=> cactiStyle si housekeeping

skyline/ionosphere/ionosphere.py
IssueID #3304: py3 - handle pymemcache bytes not str
- Explicitly set the fp_id_metric_ts_object so it always exists to be evaluated
- Wrapped literal_eval(fp_id_metric_ts_object) in try and except
Modified:
=> py3 - handle pymemcache bytes not str - fp_id_metric_ts_object

skyline/matched_or_regexed_in_list.py, updates/sql/v2.0.0-patch-3530.sql
matched_or_regexed_in_list and SQL v2.0.0-patch-3530.sql
=> matched_or_regexed_in_list

skyline/analyzer/algorithms_batch.py, skyline/analyzer/analyzer.py, skyline/analyzer/analyzer_batch.py
IssueID #3508: ionosphere_untrainable_metrics
IssueID #3514: Identify inactive metrics
IssueID #3532: Sort all time series
- Added algorithms_batch.py so there is no pollution and
analyzer and analyzer_batch are totally independent
from algorithms import run_selected_algorithm point of view and can have
separate logging
- Changed analyzer_batch to use algorithms_batch
- Identify Ionosphere untrainable metrics
- Added KNOWN_NEGATIVE_METRICS to settings
- Added run_negatives_present to the run_selected_algorithms arguments
- Added logging to the DeletedByRoomba exception as generally not related to
that but related to some other fail in the processing the run algorithms phase
- Added an update last_timestamp. …
=> batch processing improvements

skyline/crucible/crucible.py, skyline/crucible/crucible_algorithms.py
IssueID #1448: Crucible web UI
IssueID #3500: webapp - crucible_process_metrics
IssueID #3516: Handle multiple CRUCIBLE_PROCESSES
IssueID #3532: Sort all time series
- Added the functionality to Crucible to allow processing of metrics added via
the webapp Crucible page, with time series padding so that the analysis is as
similiar to the Analyzer method as possible.
- Allow for Crucible to apply alert_interval and send anomalies to Panorama
- Allow for Crucible to use multiple processes to process added jobs
- Sort all time series
Modified:
skyline/crucible/crucible_algorithms.py
=> crucible_process_metrics

skyline/panorama/panorama.py
IssueID #3522: Incorrect handling of BATCH_PROCESSING_NAMESPACES in Panorama
- Allow the check file to already hold a valid python list on one line
so that a check can be added by simply echoing to debug metric_vars
line from to log for any failed checks into a new Panorama check file
The original above pattern is still the default, this is for the check
files to be added by the operator from the log or for debugging
- Changed to redis decoded for scan_iter
Modified:
=> panorama batch processing

skyline/mirage/mirage.py, skyline/mirage/mirage_algorithms.py
IssueID #2882: Mirage - periodic_check
- Identify Ionosphere untrainable metrics
- Added KNOWN_NEGATIVE_METRICS to settings
- Added run_negatives_present to the run_selected_algorithms arguments
- Added logging to the DeletedByRoomba exception as generally not related to
that but related to some other fail in the processing the run algorithms phase
- Added an update last_timestamp. block to the Boring, Stale and Too Short
exceptions block to handle airgaps in batch metrics.
Modified:
=> Mirage ionosphere.untrainable_metrics

skyline/analyzer/alerters.py, skyline/analyzer_dev/analyzer_dev.py, skyline/boundary/boundary.py, skyline/mirage/mirage_alerters.py
IssueID #3532: Sort all time series
- Sort all time series from Redis data
Modified:
skyline/analyzer_dev/analyzer_dev.py
=> Sort all time series

skyline/analyzer/algorithms.py
IssueID #3504: Handle airgaps in batch metrics
- Changed to algorithms related to handling airgaps in batch metrics and
identifying Ionosphere untrainable_metrics
Modified:
=> algorithms - handle airgaps in batch metrics and untrainable_metrics

skyline/ionosphere/ionosphere.py
=> ionosphere.untrainable_metrics

.idea/.gitignore, .idea/inspectionProfiles/profiles_settings.xml, .idea/misc.xml, .idea/modules.xml, .idea/skyline.iml, .idea/vcs.xml
IssueID #3506: webapp api - ionosphere_untrainable_metrics
IssueID #3500: webapp - crucible_process_metrics
IssueID #1448: Crucible web UI
- Changes to webapp for the above referenced issues
Modified:
skyline/webapp/crucible_backend.py
skyline/webapp/templates/crucible.html
skyline/webapp/templates/crucible_job.html
skyline/webapp/templates/crucible_process_metrics.html
=> webapp crucible changes

skyline/webapp/ionosphere_backend.py
IssueID #3464: Optimise ionosphere_backend ionosphere_search queries
Modified:
=> Optimise ionosphere_backend ionosphere_search queries

skyline/mirage/mirage.py
IssueID #2882: Mirage - periodic_check
- Only remove training_data if not anomalous
Modified:
=> tweak mirage_periodic_check

skyline/ionosphere/ionosphere.py, skyline/webapp/ionosphere_backend.py
IssueID #3546: Change ionosphere_enabled if all features profiles are disabled
- Disable related layers when a features profile is disabled
- Set a metric to ionosphere_enabled to 0 if all features profiles are disabled
Modified:
=> handle willy nillied metrics

dev-requirements.txt, docs/analyzer.rst, docs/flux.rst, docs/getting-data-into-skyline.rst, docs/installation.rst, docs/ionosphere.rst, docs/releases.rst, docs/upload-data-to-flux.rst, requirements.txt, skyline/flux/flux.py, skyline/flux/logger.py, skyline/flux/populate_metric.py, skyline/flux/populate_metric_worker.py, skyline/flux/uploaded_data_worker.py, skyline/settings.py, skyline/webapp/templates/flux_frontend.html, skyline/webapp/templates/layout.html, skyline/webapp/templates/upload_data.html, skyline/webapp/webapp.py
IssueID #3538: webapp - upload_data endpoint
- Added webapp upload_data functionality
- Added flux process upload data functionality
Added:
skyline/webapp/templates/flux_frontend.html
skyline/webapp/templates/upload_data.html
Modified:
docs/flux.rst
docs/getting-data-into-skyline.rst
skyline/flux/logger.py
skyline/flux/populate_metric.py
skyline/webapp/templates/layout.html
=> upload_data - flux and webapp

skyline/ionosphere_functions.py
IssueID #2404: Ionosphere - fluid approximation
- Removed unrequired variable
Modified:
=> fix create_fp_ts_graph

skyline/horizon/worker.py, skyline/ionosphere/ionosphere.py, skyline/ionosphere/learn.py, skyline/luminosity/process_correlations.py, skyline/skyline_functions.py
IssueID #3572: Apply list to settings import
- Apply list to settings import
- Wrapped training_data_list in try and except in ionosphere.py (3472)
Modified:
=> Apply list to settings import

skyline/panorama/panorama.py, skyline/webapp/webapp.py
IssueID #3562; Change panorama.last_check keys to timestamp value
IssueID #3572: Apply list to settings import
- Use timestamp int and not a msgpack value, decode the key value
- Apply list to settings import
Modified:
=> Change panorama.last_check keys to timestamp value

skyline/external_alert_configs.py
- WIP external alert config
Added:
skyline/external_alert_configs.py
=> WIP - external alert config

dev-requirements.txt, docs/algorithms/custom-algorithms.rst, docs/algorithms/index.rst, requirements.txt, skyline/analyzer/alerters.py, skyline/analyzer/algorithms.py, skyline/analyzer/algorithms_batch.py, skyline/analyzer/analyzer.py, skyline/analyzer/analyzer_batch.py, skyline/custom_algorithms.py, skyline/custom_algorithms/abs_stddev_from_median.py, skyline/custom_algorithms/last_same_hours.py, skyline/custom_algorithms_to_run.py, skyline/flux/worker.py, skyline/mirage/mirage.py, skyline/mirage/mirage_algorithms.py, skyline/settings.py, tests/algorithms_test.py
IssueID #3570: Mirage - populate_redis
- Added custom algorithms functionality as referenced in 'How Does Skyline Handle
Seasonal Data' #231 (3566, 3068)
- Added functionality for Mirage to fill Redis with FULL_DURATION data
Added:
docs/algorithms/index.rst
skyline/custom_algorithms.py
skyline/custom_algorithms/abs_stddev_from_median.py
skyline/custom_algorithms/last_same_hours.py
skyline/custom_algorithms_to_run.py
Modified: …
=> custom algorithms and Mirage - populate_redis

docs/alerts.rst, docs/algorithms/custom-algorithms.rst, docs/analyzer.rst, docs/index.rst, docs/mirage.rst, docs/skyline.analyzer.rst, docs/skyline.crucible.rst, docs/skyline.rst
- docs for custom algorithms and the latest functionality
Modified:
docs/alerts.rst
docs/index.rst
docs/mirage.rst
docs/skyline.analyzer.rst
docs/skyline.crucible.rst
docs/skyline.rst
=> custom algorithm docs

skyline/analyzer/analyzer.py
IssueID #3588: Metric http_alerter queues
IssueID #3396: http_alerter
- Send metrics of the http_alerter queue sizes so they can be monitored via
Boundary checks
Modified:
=> Metric http_alerter queues

skyline/flux/uploaded_data_worker.py
- Added occassional logging
Modified:
=> Add additional debug logging

skyline/analyzer/alerters.py, skyline/boundary/boundary_alerters.py, skyline/mirage/mirage_alerters.py, skyline/slack_functions.py
IssueID #3612: Upgrade to slack v2
IssueID #3556: Update deps
- Handle changes in slackclient v2 while maintaining backwards compatibility
Modified:
skyline/slack_functions.py
=> slackclient v2

skyline/ionosphere/ionosphere.py
IssueID #3644: Do not apply ionosphere_busy to batch processing metrics
IssueID #2904: Initial Ionosphere echo load and Ionosphere feedback
IssueID #2484: FULL_DURATION feature profiles
- In the batch processing context do not apply the alternation between
normal Ionosphere Mirage features profile checks and Ionosphere echo
features profile checks when ionosphere_busy is set to True as it
results in false positives on batch processing metrics where one check
matches and the next does not, then the next does.
Modified:
=> Do not apply ionosphere_busy to batch processing metrics

skyline/analyzer/analyzer.py
IssueID #3532: Sort all time series
IssueID #3586: Change all alert pattern checks to matched_or_regexed_in_list
IssueID #3650: ROOMBA_DO_NOT_PROCESS_BATCH_METRICS
- Reduce the time to sort and deduplicate time series use Redis pipe, 10x faster
also check if the last timestamps are equal before submitting to Redis as if
they are not at this point then they will not be after
- Only test nonNegativeDerivative if the timeseries has more than 3 data points
- Always set the derivative_metric_key if it is not set
- Handle multiple metrics in base_name conversion in analyzer
- Speed up iterating all_alerts …
=> Optimize batch_processing and sorting

skyline/ionosphere/ionosphere.py
IssueID #3462: Add IONOSPHERE_MANAGE_PURGE
IssueID #3382: Prevent ionosphere.learn loop edge cases
- Added the fp full_duration for clarity sake
- Do not purge every run only if the Redis last_purge_key has expired
Modified:
=> Do not purge every run

skyline/mirage/mirage.py
PR #267
- Added MIRAGE_ALWAYS_METRICS
- Handle multiple metrics in base_name conversion
Modified:
=> MIRAGE_ALWAYS_METRICS

skyline/crucible/crucible.py
IssueID #3630: webapp - crucible_process_training_data
PR #267
- Added poc of crucible_process_training_data
Modified:
=> crucible_process_training_data

skyline/analyzer/analyzer.py
IssueID #3660: Handle flux and flux.filled lags
- Just append. In cases where the Skyline instance is not processing all the
metrics within ANALYZER_OPTIMUM_RUN_DURATION and flux is
constantly filling or populating metrics and IDENTIFY_AIRGAPS
is enabled, analyzer can get into a state where:
Sorting and de-duplicating flux metrics is never achieved on
a number of metrics as there are new data points added during
the processing period.
Analyzer never gets through the processing in ANALYZER_OPTIMUM_RUN_DURATION
as it is sorting and de-duplicating every flux metric. This
results in all the sort and de-duplication processing being
ineffective and unless.
Solution - Add any missing data points and timestamps to the
sorted and de-duplicated …
=> Handle flux and flux.filled lags

skyline/ionosphere/learn.py
IssueID #3382: Prevent ionosphere.learn loop edge cases
- Remove learn work if learn_parent_id is a recent features profile
Modified:
=> Do not relearn in window

skyline/ionosphere/ionosphere.py
- From batch_processing metrics the learn check is being added and
removed as the learn check for batch metrics happens immediately as
the learn after duration can have passed.  To the check file needs to
be loaded to determine if was added by ionosphere_learn before the
check is just removed.
Modified:
=> Do not skip analyzer_batch ionosphere_learn work

utils/dawn/skyline.dawn.sh
- Update build script and dependencies
Modified:
=> Update build script and dependencies

.travis.yml, setup.py
- Update from 2.7 to 3.8
Modified:
.travis.yml
setup.py
=> Update Python version

skyline/ionosphere_functions.py, skyline/webapp/templates/training_data.html, skyline/webapp/webapp.py
IssueID #3568: Ionosphere - report anomalies in training period
- Added labelled_anomalies to report anomalies in training period
Modified:
skyline/webapp/templates/training_data.html
=> report anomalies in training period

skyline/analyzer/agent_batch.py, skyline/analyzer/alerters.py, skyline/analyzer_dev/agent.py, skyline/analyzer_dev/analyzer_dev.py, skyline/crucible/crucible.py, skyline/flux/populate_metric_worker.py, skyline/flux/uploaded_data_worker.py, skyline/ionosphere/common_functions.py, skyline/ionosphere/ionosphere.py, skyline/mirage/mirage_alerters.py, skyline/skyline_functions.py, skyline/tsfresh_features/scripts/make-pytz.all_timezones-rst.py, skyline/tsfresh_features/scripts/pytz.rst, skyline/webapp/webapp.py, utils/python-daemon/runner.2.2.4.py, utils/seed_data.py
IssueID #3668: v2.0.0
- docstrings and bandit changes for v2.0.0
- Added daemon runner.2.2.4.py which runs on Python 3
Modified:
Added:
utils/python-daemon/runner.2.2.4.py
Modiifed:
skyline/analyzer/agent_batch.py
skyline/analyzer_dev/agent.py
skyline/analyzer_dev/analyzer_dev.py
skyline/ionosphere/common_functions.py
skyline/tsfresh_features/scripts/make-pytz.all_timezones-rst.py
skyline/tsfresh_features/scripts/pytz.rst
utils/seed_data.py
=> docstrings and bandit changes for v2.0.0

docs/releases.rst
IssueID #3668: v2.0.0
- docs for v2.0.0
=> v2.0.0 release doc

skyline/boundary/boundary_alerters.py
IssueID #3676: Boundary slack alert errors
IssueID #3612: Upgrade to slack v2
- Strange only Boundary slack messages are erroring on a tuple or part thereof,
mirage_alerters using the same method are fine?  This fix handles converting
tuple items into list items where the channel
Modified:
=> Boundary slack alert errors

skyline/crucible/crucible_algorithms.py, skyline/webapp/crucible_backend.py, skyline/webapp/templates/crucible_process_metrics.html, skyline/webapp/webapp.py
IssueID #3682: SNAB - webapp - crucible_process - run_algorithms
- Added the ability to define what algorithms to run via the crucible webapp
frontend
Modified:
skyline/crucible/crucible_algorithms.py
skyline/webapp/crucible_backend.py
skyline/webapp/templates/crucible_process_metrics.html
=> SNAB - webapp - crucible_process - run_algorithms

skyline/horizon/worker.py
IssueID #3680: horizon.worker.datapoints_sent_to_redis
- Added metric to worker horizon.worker.datapoints_sent_to_redis
Modified:
=> horizon.worker.datapoints_sent_to_redis

skyline/analyzer/alerters.py, skyline/boundary/boundary_alerters.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py, skyline/panorama/panorama.py, skyline/skyline.sql, skyline/skyline_functions.py, updates/sql/v2.1.0.sql
IssueID #3704: Add alert to anomalies
- Added an alert column to the anomalies table
- Added update_alert_ts function to panorama
- Added add_panorama_alert to skyline_finctions
- Call add_panorama_alert in alerters, mirage_alerters and boundary_alerters
- Correct indent in Mirage
Added:
updates/sql/v2.1.0.sql
Modified:
=> Add alert to anomalies table

skyline/slack_functions.py
IssueID #3710: Gracefully handle slack failures
Modified:
skyline/slack_functions.py
=> Gracefully handle slack failures

dev-requirements.txt, requirements.txt
IssueID #3720: Update SQLAlchemy - SNYK-PYTHON-SQLALCHEMY-590109
- Update Sqlalchemy from 1.3.18 to 1.3.19 - https://snyk.io/vuln/SNYK-PYTHON-SQLALCHEMY-590109
Modified:
=> Update SQLAlchemy - SNYK-PYTHON-SQLALCHEMY-590109

skyline/ionosphere/learn.py
IssueID #3382: Prevent ionosphere.learn loop edge cases
- Do not add to exisitng_recent_fps if learn_parent_id is generation 0
Modified:
=> Do not add generation 0 to exisitng_recent_fps

skyline/mirage/mirage.py
IssueID #3730: Validate Mirage running multiple processes
- Ensure Mirage spin_process can run with multiple processes
- Add additional mirage metrics checks.{done,pending,stale_discarded}
- Changed mirage sent_to_panorama and sent_to_ionosphere metrics to send every
60 seconds, rather than every run.
- Added MIRAGE_PROCESSES to settings
Modified:
=> Validate Mirage running multiple processes

skyline/analyzer/algorithms_batch.py, skyline/analyzer/analyzer_batch.py
IssueID #3684: ROOMBA_BATCH_METRICS_CUSTOM_DURATIONS
- Handle algorithm error files in analyzer_batch
- Added use_full_duration to analyzer_batch tail_avg calls
Modified:
=> ROOMBA_BATCH_METRICS_CUSTOM_DURATIONS

skyline/webapp/backend.py, skyline/webapp/ionosphere_backend.py, skyline/webapp/templates/api.html, skyline/webapp/templates/correlations.html, skyline/webapp/webapp.py
IssueID #3740: webapp - anomaly API endpoint
- Added anomaly API endpoint to return json data relating to an anomaly including
cross correlations, end_timestamp, id, metric, possible related anomaly id,
timestamp, possible related match ids and value
Modified:
skyline/webapp/templates/correlations.html
=> webapp - anomaly API endpoint

updates/sql/v2.1.0-patch-dev-3748.sql
- This is a development SQL script to patch Skyline the initial v2.1.0 and bring
the DB up to date with SNAB additions
Added:
updates/sql/v2.1.0-patch-dev-3748.sql
=> v2.1.0-patch-dev-3748.sql

skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py
- Added that anomaly_id and anomalyScore to Mirage http_alerts
Modified:
=> Add anomaly_id to http_alerter

skyline/analyzer/analyzer.py
IssueID #3766: Refresh mirage.metrics_expiration_times for batch processing
- Correct the refresh mirage.metrics_expiration_times of
Modified:
=> Refresh mirage.metrics_expiration_times

skyline/webapp/templates/api.html, skyline/webapp/webapp.py
IssueID #3770: webapp - batch_processing metrics API endoint
- Added a batch_processing_metrics API endoint
Modified:
=> webapp - batch_processing metrics API endoint

docs/SNAB.rst
IssueID #3774: SNAB_LOAD_TEST_ANALYZER
- Added SNAB_LOAD_TEST_ANALYZER to settings and the functionality to Analyzer
- Update SNAB doc
Modified:
docs/SNAB.rst
docs/index.rst
=> SNAB_LOAD_TEST_ANALYZER

skyline/mirage/mirage.py
IssueID #3776: waterfall_alert - no analyzer triggered_algorithms in waterfall_panorama_data on MIRAGE_ALWAYS_METRICS
- Populate triggered_algorithms for waterfall alerting and Panorama on
MIRAGE_ALWAYS_METRICS
Modified:
=> waterfall alerts - handle triggered_algorithms for MIRAGE_ALWAYS_METRICS

skyline/horizon/agent.py, skyline/horizon/worker.py
IssueID #3680: horizon.worker.datapoints_sent_to_redis
- Added worker_number
- Send Graphite metric for each worker
Modified:
skyline/horizon/agent.py
=> horizon Graphite metric for each worker

skyline/mirage/mirage.py
IssueID #3800: Handle feedback metrics in Mirage and waterfall alerts
- Handle feedback metrics in Mirage and waterfall alerts
Modified:
=> Handle feedback metrics in Mirage and waterfall alerts

skyline/vista/worker.py
IssueID #3796: FLUX_CHECK_LAST_TIMESTAMP
- Handle FLUX_CHECK_LAST_TIMESTAMP in vista
Modified:
skyline/vista/worker.py
=> Handle FLUX_CHECK_LAST_TIMESTAMP in vista

skyline/settings.py
IssueID #3788: snab_flux_load_test
IssueID #3808: ANALYZER_DYNAMICALLY_ANALYZE_LOW_PRIORITY_METRICS
IssueID #3810: ANALYZER_MAD_LOW_PRIORITY_METRICS
IssueID #3812: ANALYZER_ANALYZE_LOW_PRIORITY_METRICS
IssueID #3818: ANALYZER_BATCH_PROCESSING_OVERFLOW_ENABLED
IssueID #3798: FLUX_PERSIST_QUEUE
IssueID #3796: FLUX_CHECK_LAST_TIMESTAMP
- Added new settings
ANALYZER_ANALYZE_LOW_PRIORITY_METRICS = True
ANALYZER_DYNAMICALLY_ANALYZE_LOW_PRIORITY_METRICS = False
ANALYZER_MAD_LOW_PRIORITY_METRICS = 0
FLUX_VERBOSE_LOGGING = True
FLUX_PERSIST_QUEUE = False
FLUX_CHECK_LAST_TIMESTAMP = True
SNAB_CHECKS = {}
SNAB_LOAD_TEST_ANALYZER = 0
SNAB_FLUX_LOAD_TEST_ENABLED = False
SNAB_FLUX_LOAD_TEST_METRICS = 0
SNAB_FLUX_LOAD_TEST_METRICS_PER_POST = 480
SNAB_FLUX_LOAD_TEST_NAMESPACE_PREFIX = …
=> new settings

skyline/custom_algorithms/skyline_matrixprofile.py, skyline/custom_algorithms_to_run.py, skyline/mirage/mirage_algorithms.py
IssueID #3744: POC matrixprofile
- Added missing run_3sigma_algorithms and use_with parameters
Modified:
skyline/custom_algorithms/skyline_matrixprofile.py
skyline/custom_algorithms_to_run.py
=> custom_algorithms

docs/horizon.rst, skyline/flux/worker.py
IssueID #3790: flux - pickle to Graphite
- Added Redis debug sets (3790)
- Updated horizon doc (3820)
Modified:
docs/horizon.rst
=> flux - pickle to Graphite

skyline/analyzer/alerters.py, skyline/mirage/mirage_alerters.py
- Added yhat_upper, yhat_lower and yhat_real_lower to the http alerter json
Modified:
=> added yhat values

skyline/skyline_functions.py, skyline/webapp/backend.py, skyline/webapp/webapp.py
IssueID #3850: webapp - yhat_values API endoint
IssueID #2464: luminosity_remote_data
- Added yhat_values API endpoint and get_yhat_values function
- Added data_type list option to the get_graphite_metric function
- Decode Redis for unique_metrics for luminosity_remote_data and get_cluster_data
-
Modified:
=> webapp - yhat_values API endoint

skyline/analyzer/analyzer.py
IssueID #3856: Handle boring sparsely populated metrics in derivative_metrics
- Add an additional check so that the metric does not get classified on the
same data points and timestamps consecutively only new timestamps are to be
considered
Modified:
=> Handle boring sparsely populated metrics in derivative_metrics

skyline/flux/worker.py
- Log appropriately with metrics that come in at a frequency of less than 60
seconds and it being possible that the flux.metrics_data_sent key does not
exist
Modified:
=> HORIZON_SHARDS

skyline/mirage/mirage.py
- If the check just done is newer than an existing mirage waterfall alert metric
timestamp remove those keys as well
- Determine the triggered_algorithms and algorithms_run from new metric items
Modified:
=> Remove older waterfall_alerts

skyline/luminosity/process_correlations.py
IssueID #3858: skyline_functions - correlate_or_relate_with
IssueID #2464: luminosity_remote_data
- Use correlate_or_relate_with on remote_assigned to only correlate with the
configured correlation groups
- Handle remote_assigned ts_data properly
Modified:
=> Use correlate_or_relate_with in process_correlations

skyline/flux/listen.py, skyline/flux/populate_metric_worker.py, skyline/flux/worker.py
IssueID #3864: flux - try except everything
- Wrapped everything in try except
Modified:
=> flux - try except everything

skyline/boundary/boundary.py, skyline/boundary/boundary_alerters.py
IssueID #3878: Add metric_trigger and alert_threshold to Boundary alerts
- Added the metric_trigger and alert_threshold values to Boundary alerts
Modified:
=> Add metric_trigger and alert_threshold to Boundary alerts

skyline/luminosity/process_correlations.py
IssueID #3890: metrics_manager - sync_cluster_files
- Added the hostname to the REMOTE_SKYLINE_INSTANCES iterator
Modified:
=> luminosity - handle new REMOTE_SKYLINE_INSTANCES

skyline/webapp/ionosphere_backend.py
IssueID #3934: ionosphere_performance
- Added default timestamps
- Correct axes labels
Modified:
=> Fix timezone issue in ionosphere_performance

dev-requirements.txt, requirements.txt
IssueID #3970: custom_algorithm - adtk_level_shift
- Added dep to adtk fork with save plot option
Modified:
=> Add adtk dep

dev-requirements.txt, requirements.txt
IssueID #3988: SNYK-PYTHON-URLLIB3-1085966
- Mitigate CVE-2021-28363 update to 1.26.4
https://snyk.io/vuln/SNYK-PYTHON-URLLIB3-1085966
Modified:
=> Update urllib3 adtk dep

skyline/analyzer/algorithms.py
IssueID #3848: custom_algorithms - run_before_3sigma parameter
- Added run_before_3sigma parameter and logic that was added to
mirage/mirage_algorithms.py to analyzer/algorithms.py
Modified:
=> custom_algorithms - run_before_3sigma parameter

docs/readthedocs.requirements.txt
IssueID #3990: Update jinja - CVE-2020-28493
IssueID #3960: SNYK-PYTHON-JINJA2-1012994
- Update deps in line with requirements
Modified:
docs/readthedocs.requirements.txt
=> Update deps in readthedocs requirements

skyline/luminosity/luminosity.py, skyline/skyline.sql
- Added classify_metrics and classify_anomalies to luminosity
- Added new anomaly_types and anomalies_type DB tables
Modified:
skyline/luminosity/luminosity.py
=> metric and anomaly classifications

docs/flux.rst
=> Update flux docmetric and anomaly classifications

skyline/luminosity/process_correlations.py
IssueID #3956: luminosity - motifs
- Add motifs to process_correlations return
Modified:
=> Add motifs to process_correlations

skyline/luminosity/classify_anomalies.py
- Adjust mysql_insert for no PRIMARY_KEY and check for existing record
Modified:
skyline/luminosity/classify_anomalies.py
=> anomaly classifications

skyline/analyzer/analyzer_batch.py
- Remove from non_derivative_metrics as per analyzer
Modified:
=> analyse_derivatives - change in monotonicity

skyline/webapp/backend.py, skyline/webapp/templates/label_anomalies.html, skyline/webapp/templates/not_anomalous.html, skyline/webapp/templates/not_anomalous_metric.html, skyline/webapp/templates/panorama.html, skyline/webapp/webapp.py
IssueID #3994: Panorama - mirage not anomalous
- Added Panorama mirage not anomalous visualisations to webapp
-
Added:
skyline/webapp/templates/not_anomalous.html
skyline/webapp/templates/not_anomalous_metric.html
Modified:
skyline/webapp/templates/label_anomalies.html
skyline/webapp/templates/panorama.html
=> Panorama - mirage not anomalous

skyline/webapp/crucible_backend.py
IssueID #3500: webapp - crucible_process_metrics
IssueID #1448: Crucible web UI
- Use filesafe metric name for crucible_process_metrics
Modified:
skyline/webapp/crucible_backend.py
=> webapp - crucible_process_metrics

skyline/mirage/mirage.py
IssueID #3994: Panorama - mirage not anomalous
- A hash is added to the mirage.panorama.not_anomalous_metrics for every metric
that is found to be not anomalous.  This provides data for /panorama?not_anomalous
and /panorama?not_anomalous_metric method which are used for plots in the
webapp and json response (3994)
- Always determine triggered_algorithms and calculate anomalyScore for alerts (3542)
Modified:
=> mirage.panorama.not_anomalous_metrics

skyline/analyzer/alerters.py, skyline/boundary/boundary_alerters.py, skyline/functions/aws/send_sms.py, skyline/functions/settings/get_sms_recipients.py, skyline/mirage/mirage_alerters.py
- Added SMS alerts via AWS SNS
Added:
skyline/functions/aws/send_sms.py
skyline/functions/settings/get_sms_recipients.py
Modified:
=> IssueID #4196: functions.aws.send_sms

skyline/analyzer/metrics_manager.py
IssueID #4188: metrics_manager.boundary_metrics
- Build boundary metrics - metrics_manager.boundary_metrics Redis hash
IssueID #4148: analyzer.metrics_manager.resolutions
IssueID #4146: check_data_sparsity - incorrect on low fidelity and inconsistent metrics
- Never set the metric_resolution to a negative int
- Explicitly set data_sparsity
- Manage the luminosity.cloudbursts.anomalies_processed Redis hash and remove
keys that are older than 24 hours. Redis hash luminosity.cloudbursts.anomalies_processed
- metric_names_with_ids
- Added ids_with_metric_names
IssueID #4278: luminosity - related_namespaces
- Create and manage the metrics_manager.namespaces Redis hash but only update it
if new …
=> metrics_manager additions

skyline/create_matplotlib_graph.py
Modified:
skyline/create_matplotlib_graph.py
=> Added anomalies as optional parameter to create_matplotlib_graph

skyline/analyzer/analyzer.py
IssueID #4214: alert.paused
- Added alert.paused key check to analyzer
- https://github.com/earthgecko/skyline/pull/442
Modified:
=> analyzer - alerts.paused

skyline/boundary/boundary.py
IssueID #4214: alert.paused
IssueID #4166: Allow boundary to send same image to multiple slack channels
IssueID #4280: aet.metrics_manager.derivative_metrics Redis hash
- Added alert.paused key check to boundary
- Change from using derivative_metrics Redis key to
aet.metrics_manager.derivative_metrics
- Send default exceptions values to Graphite
- https://github.com/earthgecko/skyline/pull/443
Modified:
=> boundary changes

skyline/mirage/mirage.py
IssueID #4214: alert.paused
IssueID #4152: DO_NOT_SKIP_SKYLINE_FEEDBACK_NAMESPACES
- Added alert.paused key check to mirage
- Added DO_NOT_SKIP_SKYLINE_FEEDBACK_NAMESPACES functionality to mirage
- https://github.com/earthgecko/skyline/pull/444
Modified:
=> mirage - alerts.paused and DO_NOT_SKIP_SKYLINE_FEEDBACK_NAMESPACES

skyline/custom_algorithms/adtk_level_shift.py, skyline/database.py, skyline/functions/database/queries/base_name_from_metric_id.py, skyline/functions/graphite/get_metrics_timeseries.py, skyline/luminosity/agent.py, skyline/luminosity/cloudburst.py, skyline/luminosity/cloudbursts.py, skyline/luminosity/process_correlations.py, skyline/skyline.sql, updates/sql/v2.1.0-patch-4164.sql, updates/sql/v2.1.0-patch-dev-4164.sql, updates/sql/v2.1.0.sql
- Added cloudbursts changes to custom_algorithms/adtk_level_shift
- Added cloudbursts changes and cross_correlation_relationships changes to
database.py
- Added Cloudburst, Cloudbursts and RelatedMetrics to agent.py
- Use common determine_data_frequency function in process_correlations.py
(IssueID #3860: luminosity - handle low frequency data)
- Added cloudburst, cloudbursts, metric_group and metric_group_info tables to
skyline.sql
- https://github.com/earthgecko/skyline/pull/446
Added:
skyline/functions/database/queries/base_name_from_metric_id.py
skyline/functions/graphite/get_metrics_timeseries.py
skyline/luminosity/cloudburst.py
skyline/luminosity/cloudbursts.py …
=> luminosity - cloudbursts and cross_correlation_relationships

skyline/custom_algorithms/skyline_matrixprofile.py
IssueID #3744: POC matrixprofile
- Use windows parameter rather than hard coded 10
- Update docstring
- https://github.com/earthgecko/skyline/pull/449
Modified:
skyline/custom_algorithms/skyline_matrixprofile.py
=> skyline_matrixprofile - update

skyline/flux/aggregator.py
IssueID #4004: flux - aggregator.py and FLUX_AGGREGATE_NAMESPACES
- Handle newly added metrics that have not been added to
metrics_manager.flux.aggregate_namespaces.settings due to the chicken and egg
problem
- https://github.com/earthgecko/skyline/pull/450
Modified:
skyline/flux/aggregator.py
=> flux - aggregator.py - chicken and the egg

skyline/flux/flux.py, skyline/flux/prometheus.py
IssueID #4300: prometheus
IssueID #2732: Prometheus to Skyline
- Handle settings.PROMETHEUS_SETTINGS
- Added api.add_route('/prometheus/write', prometheusMetricDataPost)
- EXPERIMENTAL
- https://github.com/earthgecko/skyline/pull/451
Added:
skyline/flux/prometheus.py
Modified:
=> flux - prometheus

skyline/flux/listen.py
IssueID #4284: flux - telegraf
IssueID #4004: flux - aggregator.py and FLUX_AGGREGATE_NAMESPACES
IssueID #4000: EXTERNAL_SETTINGS
- Allow the key to be passed as a HTTP header rather than in the json payload
- Changed to return 401 if bad key instead of 400
- Added aggregate list item
- Add skyline.external_settings flux_token elements as valid_keys
- https://github.com/earthgecko/skyline/pull/452
Modified:
=> flux - telegraf

skyline/webapp/luminosity_backend.py
- reduce os.walk
- limit default results
- https://github.com/earthgecko/skyline/pull/454
Modified:
skyline/webapp/luminosity_backend.py
=> luminosity - classify_metrics - limit results

skyline/custom_algorithms_to_run.py, skyline/functions/database/queries/get_all_db_metric_names.py, skyline/functions/database/queries/query_anomalies.py, skyline/functions/metrics/get_base_name_from_metric_id.py, skyline/functions/metrics/get_base_names_and_metric_ids.py, skyline/functions/metrics/get_metric_id_from_base_name.py, skyline/functions/metrics/get_metric_ids_and_base_names.py, skyline/functions/pandas/timeseries_to_datetime_indexed_df.py, skyline/ionosphere_functions.py, skyline/luminosity/luminosity.py, skyline/webapp/templates/classify_metrics.html
- Added optional with_ids to return metric_names, metric_names_with_ids in
get_all_db_metric_names.py
- Reduce query_anomalies query
- Correct log typo in ionosphere_functions.py
- Mixed tab space formatting in ionosphere_functions.py from (IssueID #4102: Merge luminosity.PR429) #429
- Added timeseries_to_datetime_indexed_df
- List keys in custom_algorithms_to_run
- https://github.com/earthgecko/skyline/pull/455
Added:
skyline/functions/metrics/get_base_name_from_metric_id.py
skyline/functions/metrics/get_base_names_and_metric_ids.py
skyline/functions/metrics/get_metric_id_from_base_name.py
skyline/functions/metrics/get_metric_ids_and_base_names.py
skyline/functions/pandas/timeseries_to_datetime_indexed_df.py
Modified: …
=> misc changes and fixes

skyline/webapp/get_snab_results.py, skyline/webapp/templates/layout.html, skyline/webapp/templates/snab.html
- Added cloudburst and snab results UI
- https://github.com/earthgecko/skyline/pull/456
Added:
skyline/webapp/get_snab_results.py
skyline/webapp/templates/snab.html
Modified:
skyline/webapp/templates/classify_metrics.html
skyline/webapp/templates/layout.html
=> cloudburts and snab results ui

skyline/functions/metrics/get_metric_latest_anomaly.py, skyline/functions/panorama/update_metric_latest_anomaly.py, skyline/functions/redis/get_redis_metrics_timeseries.py, skyline/panorama/panorama.py, skyline/webapp/templates/luminosity.html, updates/sql/v2.1.0-patch-dev-4264.sql
IssueID #4268: Redis hash key - panorama.metrics.latest_anomaly
- Added functions
- Added SQL to create metric_group and metric_group_info tables
- Added related_metrics to UI
- Added panorama.metrics.latest_anomaly
- https://github.com/earthgecko/skyline/pull/457
Added:
skyline/functions/metrics/get_metric_latest_anomaly.py
skyline/functions/panorama/update_metric_latest_anomaly.py
skyline/functions/redis/get_redis_metrics_timeseries.py
updates/sql/v2.1.0-patch-dev-4264.sql
Modified:
skyline/webapp/templates/luminosity.html
=> Related metrics

skyline/functions/thunder/alert_on_no_data.py, skyline/functions/thunder/no_data.py, skyline/functions/thunder/stale_metrics.py
IssueID #1444: thunder
- Handle data['status'] == 'removed'
- Remove any entries that have been specified
- https://github.com/earthgecko/skyline/pull/458
Modified:
skyline/functions/thunder/alert_on_no_data.py
skyline/functions/thunder/no_data.py
skyline/functions/thunder/stale_metrics.py
=> thunder - misc changes

skyline/thunder/thunder.py, skyline/thunder/thunder_alerters.py
IssueID #4258: cleanup thunder.events
Modified:
skyline/thunder/thunder.py
skyline/thunder/thunder_alerters.py
=> cleanup thunder.events

skyline/mirage/mirage_algorithms.py
- Added mirage.trigger_history Redis hash
- Added trigger_history_override parameter to custom_algorithm parameters
- https://github.com/earthgecko/skyline/pull/461
Modified:
=> Mirage custom_algorithm - trigger_history_override

skyline/webapp/ionosphere_backend.py
IssueID #4206: webapp - saved_training_data page
IssueID #4246: label_anomalies - update slack thread
IssueID #4168: webapp/ionosphere_backend.py - handle old features profile dir not been found
IssueID #2476: Label and relate anomalies
- Added saved_training_data page
- Added algorithms_run key
- https://github.com/earthgecko/skyline/pull/461
Modified:
=> misc webapp ionosphere_backend changes

skyline/webapp/get_saved_training_data.py, skyline/webapp/templates/saved_training_data.html
IssueID #4206: webapp - saved_training_data page
- Added saved_training_data page
- https://github.com/earthgecko/skyline/pull/463
Added:
skyline/webapp/get_saved_training_data.py
skyline/webapp/templates/saved_training_data.html
=> webapp - saved_training_data page

skyline/webapp/get_boundary_metrics.py
IssueID #4188: metrics_manager.boundary_metrics
- Added webapp function
- https://github.com/earthgecko/skyline/pull/464
Added:
skyline/webapp/get_boundary_metrics.py
=> webapp - get_boundary_metrics

skyline/webapp/templates/api.html, skyline/webapp/templates/features_profiles.html, skyline/webapp/templates/ionosphere.html, skyline/webapp/templates/motif_matches.html, skyline/webapp/templates/search_features_profiles.html, skyline/webapp/templates/training_data.html, skyline/webapp/webapp.py
IssueID #4168: webapp/ionosphere_backend.py - handle old features profile dir not been found
IssueID #4188: metrics_manager.boundary_metrics
IssueID #4206: webapp - saved_training_data page
IssueID #1444: thunder
IssueID #3884: ANALYZER_CHECK_LAST_TIMESTAMP
IssueID #4280: aet.metrics_manager.derivative_metrics Redis hash
- Added webapp functions, features and fixes for the abovementioned issues
- https://github.com/earthgecko/skyline/pull/465
Modified:
skyline/webapp/templates/features_profiles.html
skyline/webapp/templates/ionosphere.html
skyline/webapp/templates/motif_matches.html …
=> webapp - for new features and fixes

skyline/functions/plots/plot_anomalies.py
- Added plot_anomalies.py
Added:
skyline/functions/plots/plot_anomalies.py
=> snab results ui

skyline/analyzer/metrics_manager.py, skyline/functions/database/queries/get_all_db_metric_names.py, skyline/functions/graphite/get_metrics_timeseries.py, skyline/functions/redis/check_key.py, skyline/functions/redis/self_check_key.py, skyline/horizon/listen.py, skyline/horizon/prometheus.py, skyline/horizon/worker.py, skyline/ionosphere_functions.py, skyline/luminosity/related_metrics.py, skyline/mirage/mirage.py, skyline/mirage/mirage_alerters.py, skyline/webapp/backend.py, skyline/webapp/ionosphere_performance.py, skyline/webapp/templates/rebrow_login.html
IssueID #4030: refactoring
IssueID #4328: BATCH_METRICS_CUSTOM_FULL_DURATIONS
- Miscellaneous logging and typing changes and related minor bug fixes
Modified:
skyline/functions/database/queries/get_all_db_metric_names.py
skyline/functions/graphite/get_metrics_timeseries.py
skyline/functions/redis/check_key.py
skyline/functions/redis/self_check_key.py
skyline/horizon/listen.py
skyline/horizon/prometheus.py
skyline/luminosity/related_metrics.py
skyline/webapp/ionosphere_performance.py
skyline/webapp/templates/rebrow_login.html
=> Miscellaneous logging and typing changes and minor bug fixes

skyline/webapp/panorama_plot_anomalies.py, skyline/webapp/templates/label_anomalies.html, skyline/webapp/templates/not_anomalous.html, skyline/webapp/templates/not_anomalous_metric.html, skyline/webapp/templates/panorama.html, skyline/webapp/templates/plot_metric_anomalies.html, skyline/webapp/webapp.py
IssueID #4326: webapp - panorama_plot_anomalies
- Added UI method to plot anomalies
Added:
skyline/webapp/panorama_plot_anomalies.py
skyline/webapp/templates/plot_metric_anomalies.html
Modified:
skyline/webapp/templates/label_anomalies.html
skyline/webapp/templates/not_anomalous.html
skyline/webapp/templates/not_anomalous_metric.html
skyline/webapp/templates/panorama.html
=> webapp - panorama_plot_anomalies

skyline/analyzer/analyzer_batch.py
IssueID #4322: Handle historical batch metrics full duration
Modified:
=> Handle historical batch metrics full duration

docs/luminosity.rst
- Update luminosity doc with related metrics
Modified:
docs/luminosity.rst
=> Update luminosity doc

readme.md
=> Remove master unstable text

docs/algorithms/custom-algorithms.rst, skyline/settings.py
=> Update docstrings and doc for trigger_history_override

docs/installation.rst
#484 highlighted this was in build script and upgrade notes but not in the installation doc
Modified:
=> Add runner patch notes to intallation doc

skyline/luminosity/process_correlations.py
IssueID #3860: luminosity - handle low frequency data
- Only if resolution is known
Modified:
=> luminosity - handle low frequency data

skyline/webapp/templates/traceback.html, skyline/webapp/webapp.py
IssueID #4344: Update dependencies
IssueID #4362: snyk - numpy and pillow updates
- Handle PyJWT change
- Update link on traceback page
Modified:
skyline/webapp/templates/traceback.html
=> webapp - Handle PyJWT change

skyline/webapp/backend.py
- Fix deleted namespace
Modified:
=> IssueID #4362: snyk - numpy and pillow updates

skyline/boundary/boundary_alerters.py
IssueID #4366: Fix boundary slack channels match
Modified:
=> Fix boundary slack channels match

dev-requirements.txt, requirements.txt
IssueID #4368: Switch git clone to https
Modified:
=> Switch git clone to https

skyline/vista/fetcher.py
- Remove old unprocessed entries from the vista.fetcher.metrics.json Redis set
- Update the sent_to_flux metric to include both metrics sent directly to flux
and metrics sent to flux for pre-populating
Modified:
skyline/vista/fetcher.py
=> IssueID #4370: Manage vista.fetcher.metrics.json Redis set

skyline/mirage/mirage_algorithms.py
- Set default base_name and custom_algorithms_to_run
Modified:
=> IssueID #3566: custom_algorithms

dev-requirements.txt, requirements.txt
IssueID #3538: webapp - upload_data endpoint
IssueID #4362: snyk - numpy and pillow updates
- Added openpyxl==3.0.9
Modified:
=> New dependency for pandas reading xls

skyline/webapp/webapp.py
IssueID #4374: webapp - handle url encoded chars
- WIP - webapp - handle url encoded chars
Modified:
=> WIP - webapp - handle url encoded chars

skyline/analyzer/analyzer.py
- do not do monotonic_count on batch metrics
Modified:
=> IssueID #4386: analyzer - do not do monotonic_count on batch metrics

skyline/ionosphere/ionosphere.py
- If a metric has fps but has no fps of the same duration then ionosphere
should send this as an anomaly to Panorama
Modified:
=> IssueID #4394: ionosphere - handle edge case of no fps of same duration

skyline/functions/settings/get_custom_stale_period.py
- Change variable from custom_stale_period to custom_stale_period_int
Modified:
skyline/functions/settings/get_custom_stale_period.py
=> IssueID #4076: CUSTOM_STALE_PERIOD

skyline/flux/listen.py, skyline/functions/thunder/alert_on_quota_exceeded.py, skyline/thunder/thunder.py
- Added thunder alert for metric_quota_exceeded
Added:
skyline/functions/thunder/alert_on_quota_exceeded.py
Modified:
skyline/thunder/thunder.py
=> IssueID #4412: flux - quota - thunder alert

docs/flux.rst
=> IssueID #4284: flux - telegraf

skyline/flux/populate_metric_worker.py
- Handle list index out of range as a warning
Modified:
=> IssueID #3864: flux - try except everything

skyline/functions/settings/manage_external_settings.py, skyline/slack_functions.py
Modified:
skyline/functions/settings/manage_external_settings.py
skyline/slack_functions.py
=> IssueID #4448: Handle missing slack response

skyline/webapp/templates/api.html, skyline/webapp/webapp.py
- Added inactive_metrics API method
Modified:
=> IssueID #4444: webapp - inactive_metrics

skyline/horizon/worker.py
- Added horizon.skip_metrics and horizon.do_not_skip_metrics Redis hash keys to
refer to and THEN if not found use in_skip_list
Modified:
=> IssueID #4446: Optimise horizon worker in_skip_list

skyline/functions/settings/get_external_settings.py, skyline/functions/settings/manage_external_settings.py
- Added overridden key to record what was overridden
- Wrapped in try
Modified:
skyline/functions/settings/get_external_settings.py
skyline/functions/settings/manage_external_settings.py
=> IssueID  #4442: settings - LOCAL_EXTERNAL_SETTINGS

skyline/crucible/crucible.py, skyline/crucible/crucible_algorithms.py, skyline/webapp/templates/crucible_process_metrics.html
Add custom_algorithms to crucible
=> crucible - custom_algorithms

docs/releases.rst
IssueID #4538: v3.0.0
GH #526 - v3.0.0
Modified:
docs/releases.rst
=> v3.0.0 release doc

skyline/analyzer/analyzer.py, skyline/analyzer/analyzer_batch.py, skyline/boundary/boundary.py, skyline/functions/illuminance/add_illuminance_entries.py, skyline/functions/metrics/correlate_or_relate_with.py, skyline/luminosity/process_correlations.py, skyline/mirage/mirage.py, skyline/skyline_functions.py
IssueID #2580: illuminance
- Added illuminance Redis hashes to track all anomalous events for future R&D
Added:
skyline/functions/illuminance/add_illuminance_entries.py
Modified:
=> illuminance Redis hashes

skyline/functions/metrics/get_metric_analysed_events.py, skyline/webapp/api_get_analysed_events.py, skyline/webapp/api_get_metric_analysed_events.py, skyline/webapp/backend.py, skyline/webapp/get_analysed_events.py, skyline/webapp/templates/api.html, skyline/webapp/webapp.py
IssueID #4530: namespace.analysed_events
- Added functions and API methods and documentation
IssueID #4544: Handle EXTERNAL_SETTINGS in correlate_or_relate_with
IssueID #3858: skyline_functions - correlate_or_relate_with
- Change from using skyline_functions correlate_or_relate_with to
functions.metrics.correlate_or_relate_with in webapp
Added:
skyline/functions/metrics/get_metric_analysed_events.py
skyline/webapp/api_get_analysed_events.py
skyline/webapp/api_get_metric_analysed_events.py
skyline/webapp/get_analysed_events.py
Modified:
=> namespace.analysed_events

docs/releases.rst
IssueID #4552: v3.0.2
- Correct releases doc
Modified:
docs/releases.rst
=> v3.0.2 (2)

docs/development/dawn.rst
IssueID #4552: v3.0.2
- Update dawn version
Modified:
docs/development/dawn.rst
=> v3.0.2 dawn

docs/releases/3_0_4.rst
IssueID #4562: v3.0.4
- Change version to v3.0.4
- Correct changes
Modified:
docs/releases/3_0_4.rst
=> v3.0.4 (2)

skyline/panorama/panorama.py
IssueID #2732: Prometheus to Skyline
IssueID #3442: Panorama - add metric to metrics table immediately
IssueID #4022: Move mysql_select calls to SQLAlchemy
IssueID #4300: prometheus
IssueID #4778: v4.0.0 - update dependencies
IssueID #4816: Handle error in sqlalchemy change
IssueID #4848: mirage - analyse.irregular.unstable.timeseries.at.30days
Modified:
=> panorama v4.0.0 changes and additions

etc/skyline.conf, etc/systemd/system/analyzer.service, etc/systemd/system/analyzer_batch.service, etc/systemd/system/boundary.service, etc/systemd/system/crucible.service, etc/systemd/system/flux.service, etc/systemd/system/horizon.service, etc/systemd/system/ionosphere.service, etc/systemd/system/luminosity.service, etc/systemd/system/mirage.service, etc/systemd/system/panorama.service, etc/systemd/system/snab.service, etc/systemd/system/snab_flux_load_test.service, etc/systemd/system/thunder.service, etc/systemd/system/vista.service, etc/systemd/system/webapp.service
- Changed to python 3.8.17
Modified:
etc/skyline.conf
etc/systemd/system/analyzer.service
etc/systemd/system/analyzer_batch.service
etc/systemd/system/boundary.service
etc/systemd/system/crucible.service
etc/systemd/system/flux.service
etc/systemd/system/horizon.service
etc/systemd/system/ionosphere.service
etc/systemd/system/luminosity.service
etc/systemd/system/mirage.service
etc/systemd/system/panorama.service
etc/systemd/system/snab.service
etc/systemd/system/snab_flux_load_test.service
etc/systemd/system/thunder.service
etc/systemd/system/vista.service
etc/systemd/system/webapp.service
=> IssueID #4962: Build and test skyline v4.0.0

dev-requirements.txt, docs/algorithms/custom-algorithms.rst, docs/algorithms/dbscan.rst, docs/algorithms/index.rst, docs/algorithms/isolation_forest.rst, docs/algorithms/lof.rst, docs/algorithms/m66.rst, docs/algorithms/macd.rst, docs/algorithms/mstl.rst, docs/algorithms/one_class_svm.rst, docs/algorithms/pca.rst, docs/algorithms/prophet.rst, docs/algorithms/spectral_entropy.rst, docs/algorithms/spectral_residual.rst, docs/external_settings.rst, docs/getting-started.rst, docs/index.rst, docs/installation.rst, docs/overview.rst, docs/prometheus.rst, docs/readthedocs.requirements.txt, docs/running-in-python-virtualenv.rst, requirements.txt
IssueID #4962: Build and test skyline v4.0.0
IssueID #4974: v4.0.0
- Update protobuf==3.20.1 to 3.20.3 now mysql-connector-python==8.0.33 [requires: protobuf>=3.11.0,<=3.20.3] (closes #624)
- Added placeholder algorithms docs pages referring to the source
- Minor changes to some docs
Added:
docs/algorithms/dbscan.rst
docs/algorithms/isolation_forest.rst
docs/algorithms/lof.rst
docs/algorithms/m66.rst
docs/algorithms/macd.rst
docs/algorithms/mstl.rst
docs/algorithms/one_class_svm.rst
docs/algorithms/pca.rst
docs/algorithms/prophet.rst
docs/algorithms/spectral_entropy.rst
docs/algorithms/spectral_residual.rst
Modified:
docs/algorithms/index.rst
docs/external_settings.rst
docs/getting-started.rst
docs/index.rst …
=> docs v4.0.0 changes and additions
