earthgecko/skyline

src/horizon/listen.py

At the moment when f.ex. carbon-relay will be restarted
on the other side listener will end up in infinite loop
reading 0 bytes all the time.
When a recv returns 0 bytes, it means the other side has closed
(or is in the process of closing) the connection -
https://docs.python.org/2/howto/sockets.html

Break the loop when connection closes.

---

skyline/skyline.sql

Prevents a ```ERROR 1046 (3D000) at line 16: No database selected```

Add use skyline;

---

docs/alert-testing.rst

in most places on docs the default project name is skyline-py2712

make PROJECT consistent

---

docs/releases/1_2_12.rst

IssueID #2872: v1.2.12
- Downgrade release v1.2.12 to a pre-relese in the docs with reason
Modified:
docs/releases/1_2_12.rst

Downgrade v1.2.12

---

skyline/analyzer/analyzer.py

IssueID #2824: Test redis-py upgrade
IssueID #2926: Update dependencies
- redis-py 3.x only accepts user data as bytes, strings or numbers.  Use str
with ionosphere_training_data_key_data
Modified:

redis-py upgrade

---

skyline/analyzer/algorithms.py

Hi,
The scipy.std() compute the **population standard deviation** while in Pandas Series.std() computes **sample standard deviation**. 
Refer to [standard deviation wiki](https://en.wikipedia.org/wiki/Standard_deviation) for details.
In time series data, the accquired data is not the whole data. So i think we should use **sample standard deviation** to do anomaly detection.
Thanks a lot.

Update least_squares & grubbs algorithms by using sample standard deviation

---

skyline/flux/flux.py
skyline/flux/gunicorn.py
skyline/flux/listen.py
skyline/flux/logger.py
skyline/flux/populate_metric.py
skyline/flux/populate_metric_worker.py
skyline/flux/worker.py

IssueID #3254: flux.populateMetricQueue Full
- Set Queue size to 0 infinite
- Consolidate flux logging
Modified:
skyline/flux/gunicorn.py
skyline/flux/logger.py
skyline/flux/populate_metric.py

flux py3 changes

---

skyline/horizon/agent.py
skyline/horizon/listen.py
skyline/horizon/roomba.py

Modified:
skyline/horizon/agent.py
skyline/horizon/listen.py
skyline/horizon/roomba.py

horizon py3 changes

---

skyline/luminosity/agent.py
skyline/luminosity/luminosity.py
skyline/luminosity/process_correlations.py

Modified:
skyline/luminosity/agent.py
skyline/luminosity/luminosity.py

luminosity py3 changes

---

skyline/mirage/agent.py
skyline/mirage/mirage_alerters.py
skyline/mirage/mirage_algorithms.py

IssueID #3290: Handle urllib2 in py3
- Handle urllib2 in py3 - deprecated old method now using get_graphite_graph_image
function
Modified:
skyline/mirage/agent.py

mirage py3 changes

---

skyline/webapp/webapp.py

IssueID #3230: users DB table
IssueID #2516: Add label to features profile
- Allow the user_id to be passed as a request argument
Modified:

ionsphere - Allow the user_id to be passed as a request argument

---

skyline/analyzer/alerters.py
skyline/analyzer/algorithms.py
skyline/analyzer/analyzer.py
skyline/boundary/boundary.py
skyline/boundary/boundary_alerters.py
skyline/boundary/boundary_algorithms.py
skyline/ionosphere/ionosphere.py
skyline/ionosphere/learn.py
skyline/ionosphere_functions.py
skyline/mirage/mirage.py
skyline/mirage/mirage_alerters.py
skyline/settings.py
skyline/webapp/webapp.py
utils/verify_alerts.py

IssueID #3396: http_alerter
IssueID #3406: Allow for no_email SMTP_OPTS
- Added changes to analyzer.py, alerters.py, mirage.py, mirage_alerters.py,
boundary.py and boundary_alerters.py related to the addition of a http_alerter
alert type (3396)
- Added http_alerter_ example to ALERTS and BOUNDARY_METRICS and added
HTTP_ALERTERS_OPTS and BOUNDARY_HTTP_ALERTERS_OPTS to settings.py (3396)
- Added mock_api alert_receiver endpoint to webapp.py for testing (3396)
- Allow Analyzer to identify air gapped metrics, handled in algorithms.py,
webapp.py via /api?airgapped_metrics and in settings.py (3400)
- Allow for the use of 'no_email' in SMTP_OPTS to fake email.  Allowed for in
alerters.py and mirage_alerters.py (3406)
- Use …

new features

---

skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #3422: webapp api - alerting_metrics and non_alerting_metrics
IssueID #3424: webapp - api documentation
- Added alerting_metrics and non_alerting_metrics webapp API endpoint methods
to return aet.analyzer.non_smtp_alerter_metrics and
aet.analyzer.smtp_alerter_metrics Redis sets as json (3422)
- Added initial blocks for documentation of the webapp API methods (3424)
Added:
Modified:

webapp api - alerting_metrics and non_alerting_metrics

---

skyline/panorama/panorama.py
skyline/settings.py

IssueID #3442: Panorama - add metric to metrics table immediately
- Added PANORAMA_INSERT_METRICS_IMMEDIATELY to settings
- Added the ability for Panorama to insert all metrics into the metrics table
as soon as they appear Redis.
Modified:

Panorama - add metric to metrics table immediately

---

skyline/webapp/templates/api.html
skyline/webapp/webapp.py

- Added the airgap_filled api method to allow for the removal of an entry from
the analyzer.airgapped_metrics Redis set.
- Added the beginnings of some api documentation.
Modified:

Added airgap_filled api method

---

skyline/ionosphere/ionosphere.py
skyline/settings.py

IssueID #3462: Add IONOSPHERE_MANAGE_PURGE
IssueID #3474: webapp api - training_data
- Add IONOSPHERE_MANAGE_PURGE setting and wrapped Ionosphere purging up in a
conditional to allow the user to offload purging to a script and cron if they
so desire for any reason.
- Added the ionosphere.training_data set from training_data that is not purged
and contains the correct training_data files, which is added the Redis set
which is used by the IssueID #3474: webapp api - training_data API method.
Modified:

ionosphere additions

---

skyline/skyline.sql
updates/sql/v2.0.0.sql

IssueID #3478: sql_versions table
- Added a versions table to the DB as a method to track what version of the DB
schema is being run. This eases tracking and skipping versions by know what DB
updates need to be applied (3478)
Modified:
updates/sql/v2.0.0.sql

sql_versions

---

skyline/ionosphere/learn.py

IssueID #1854: Ionosphere learn
- IONOSPHERE_LEARN_NAMESPACE_CONFIG handle 0 learn_full_duration_days
Handle if the IONOSPHERE_LEARN_NAMESPACE_CONFIG is configured with
an impossible default learn_full_duration_days of 0 e.g.
(".*", 0, 3661, 16, 100),
Modified:

IONOSPHERE_LEARN_NAMESPACE_CONFIG handle 0 learn_full_duration_days

---

bin/flux.d

IssueID #956: flux
- Change sleep to 2 seconds as on a loaded system this can take a while to
start
Modified:
bin/flux.d

sleep 2 in flux.d

---

skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #3474: webapp api - training_data
- Allow to match namespaces too
Modified:

webapp api - training_data

---

skyline/luminosity/process_correlations.py

IssueID #2270: luminosity
- Changed to use the aet Redis set, used to determine and record the
anomaly_end_timestamp, some transient sets need to copied so that
the data always exists, even if it is sourced from a transient set
Modified:

Use aet.analyzer.smtp_alerter_metrics Redis set in luminosity

---

docs/upload-data-to-flux.rst
skyline/flux/uploaded_data_worker.py
skyline/webapp/templates/upload_data.html
skyline/webapp/webapp.py

IssueID #3538: webapp - upload_data endpoint
- Added ability to ignore_submitted_timestamps to enable no checking of the
flux.last metric key and simply submit data to Graphite
- Added xls format
Modified:
skyline/webapp/templates/upload_data.html

upload_data - flux and webapp

---

skyline/analyzer/analyzer.py
skyline/flux/uploaded_data_worker.py
skyline/webapp/webapp.py

- Sort Redis data if upload has passed the ignore_submitted_timestamps using the
flux.sort_and_dedup.metrics Redis set
- Change 0 to None on columns_to_ignore and columns_to_process in webapp
Modified:

flux.uploaded_data_worker - flux.sort_and_dedup.metrics

---

skyline/analyzer/analyzer.py
skyline/analyzer/analyzer_batch.py
skyline/skyline_functions.py

- Ensure derivative metic key is always set in both analyzer and analyzer_batch
to prevent analyzer removing the metric from the derivative_metrics when the
metric is identified and added as such in analyzer_batch (3480, 2050)
- In skyline_functions.py only apply strictly_increasing_monotonicity to time
series that have sufficient data to make this determination (3480, 2050)
- Check to non 3sigma algorithm errors too in analyzer, added
check_algorithm_errors to replace settings.ALGORITHMS in the check for errors
which appends negatives_present and identify_airgaps to the ALGORITHMS to
check for errors …

Ensure derivative metic key is always set

---

docs/algorithms/custom-algorithms.rst
skyline/analyzer/analyzer.py
skyline/mirage/mirage_algorithms.py
skyline/settings.py

- Added settings.MIRAGE_ALWAYS_METRICS to allow for custom algorithms to be run
on specified metrics on every run.
Modified:

custom algorithms - MIRAGE_ALWAYS_METRICS

---

skyline/analyzer/analyzer.py
skyline/settings.py

IssueID #3570: Mirage - populate_redis
- Defined metric_flux_filled_key bug outside original conditional block as there
is now 3 conditions which can set sort_data and it fails to interpolate this
variable sometimes when mirage_filled (3570)
- Remove entries from the current.anomalies set if the timestamp is older than
FULL_DURATION (3306)
- Added some additional debug logging and corrected DEBUG_CUSTOM_ALGORITHMS
docstring (3566)
Modified:

metric_flux_filled_key bug & remove entries from the current.anomalies

---

skyline/flux/uploaded_data_worker.py

- If there are greater than 4000 datapoints sleep a little between pickles
Modified:

flux.uploaded_data_worker - sleep a bit

---

skyline/analyzer/alerters.py
skyline/analyzer/analyzer.py
skyline/mirage/mirage.py
skyline/mirage/mirage_alerters.py

- Changed external alerter expiry key to the alerter id rather than the alerter,
to send alerts for every defined external alerter rather than per alerter
- Added external alerter id to the alert json
Modified:

Change all external alerter expiry key to id

---

skyline/ionosphere/ionosphere.py
skyline/webapp/templates/rebrow_login.html

IssueID #3474: webapp api - training_data
- Added occassional logging for monitoring during training_data purge and
training_data Redis set creation
Modified:

Add additional logging to purge

---

docs/flux.rst
docs/upload-data-to-flux.rst
skyline/boundary/boundary.py
skyline/boundary/boundary_algorithms.py

IssueID #3586: Change all alert pattern checks to matched_or_regexed_in_list
IssueID #3594: Add timestamp to ENABLE_BOUNDARY_DEBUG output
- Changed original alert matching pattern to use new matched_or_regexed_in_list
function
- Add timestamp to ENABLE_BOUNDARY_DEBUG output
- Update flux docs
Modified:
docs/flux.rst
skyline/boundary/boundary_algorithms.py

alert pattern changes

---

skyline/analyzer/analyzer.py

- Handle no SECOND_ORDER_RESOLUTION_FULL_DURATION
Modified:

Fix mirage check for non mirage metric

---

skyline/ionosphere/ionosphere.py

- Report app up to stop other apps not finding the ionosphere key in Redis when
a long training_data purge runs
Modified:

Report app up on long training_data purge

---

skyline/mirage/mirage.py

- Remove pass on except and just set to default of None
Modified:

Set default external_alerter_alerter to None

---

skyline/analyzer/agent.py

IssueID #3644: #3608: Update Skyline to Python 3.8.3 and deps
- Use a shorter timeseries for quicker start up
Modified:
skyline/analyzer/agent.py

Use a shorter timeseries for quicker start up

---

skyline/analyzer/alerters.py
skyline/luminosity/process_correlations.py
skyline/mirage/mirage_alerters.py
skyline/panorama/panorama.py
skyline/webapp/backend.py

Handle multiple metrics in base_name conversion

---

skyline/analyzer/analyzer_batch.py
skyline/horizon/roomba.py
skyline/settings.py

IssueID #3650: ROOMBA_DO_NOT_PROCESS_BATCH_METRICS
- Added ROOMBA_DO_NOT_PROCESS_BATCH_METRICS to horizon/roomba.py, settings.py
and analyzer/analyzer_batch.py to allow analyzer_batch to allow for roomba.py
to not remove data points before analyzer_batch has analyzed them and enable
analyzer_batch to euthanize the batch metric keys.
- In analyzer_batch if multiple work items exist and the timestamp in the work
item is older than the last analyzed timestamp reported by Redis key, just
skip and remove the work item.
- Euthanize keys if not done in roomba, allows for backfill processing via
analyzer_batch
- Handle multiple metrics in base_name conversion in …

ROOMBA_DO_NOT_PROCESS_BATCH_METRICS

---

skyline/webapp/crucible_backend.py
skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/crucible_process_metrics.html
skyline/webapp/templates/features_profiles.html
skyline/webapp/templates/training_data.html
skyline/webapp/webapp.py

IssueID #3464: Optimise ionosphere_backend ionosphere_search queries
IssueID #3648: webapp - fp_search - do not use Redis metric check
IssueID #3630: webapp - crucible_process_training_data
IssueID #3634: webapp - ionosphere - report number of data points
IssueID #1996: Ionosphere - matches page
Modified:
skyline/webapp/crucible_backend.py
skyline/webapp/templates/crucible_process_metrics.html
skyline/webapp/templates/features_profiles.html
skyline/webapp/templates/training_data.html

webapp optimisation and crucible_process_training_data

---

skyline/analyzer/analyzer.py
skyline/ionosphere/ionosphere.py
skyline/mirage/mirage.py

IssueID #3462: Add IONOSPHERE_MANAGE_PURGE
- Reduce the running of purge_old_data_dirs in ionosphere.py so that when there
is a lot of training_data the I/O is reduced.
- Add training_data items to the ionosphere.training_data in both Analyzer and
Mirage as appropriate as Ionosphere is no longer creating the up to date set
every run.
Modified:

Add to ionosphere.training_data set

---

skyline/settings.py
skyline/skyline_functions.py
skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/training_data.html
skyline/webapp/webapp.py

IssueID #3654: IONOSPHERE_GRAPHITE_NOW_GRAPHS_OVERRIDE
- Allow to override the Graphite NOW graphs with Graphite THEN graphs
Modified:
skyline/webapp/templates/training_data.html

IONOSPHERE_GRAPHITE_NOW_GRAPHS_OVERRIDE

---

docs/upload-data-to-flux.rst
skyline/flux/uploaded_data_worker.py

- Handle unix timestamps
Modified:

uploaded_data_worker - Handle unix timestamps

---

skyline/analyzer/analyzer.py
skyline/mirage/mirage.py

IssueID #3662: Change mirage.last_check keys to timestamp value
- Add the mirage metric and its EXPIRATION_TIME to the mirage.metrics_expiration_times
Redis set in Analyzer so that Mirage can determine the metric EXPIRATION_TIME
without having to create and iterate the all_alerts object in the Mirage analysis
phase so that the reported anomaly timestamp can be used to determine whether
the EXPIRATION_TIME should be applied to a batch metric in the alerting and
Ionosphere contexts
Modified:

Change mirage.last_check keys to timestamp value

---

docs/conf.py

- Commented out failing matplotlib.sphinxext.only_directives from extensions
Modified:
docs/conf.py

Remove failing extension

---

skyline/horizon/roomba.py

IssueID #3650: ROOMBA_DO_NOT_PROCESS_BATCH_METRICS
- Correct typo
Modified:
skyline/horizon/roomba.py

Correct typo

---

docs/SNAB.rst
docs/ionosphere.rst
skyline/features_profile.py
skyline/ionosphere/agent.py
skyline/ionosphere/ionosphere.py
skyline/ionosphere_functions.py
skyline/settings.py
skyline/skyline_functions.py
skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/training_data.html
skyline/webapp/webapp.py

IssueID #3670: IONOSPHERE_CUSTOM_KEEP_TRAINING_TIMESERIES_FOR
- Allowing training data to be kept indefinitely for certain metrics and to
train from this historical training data
- Added related settings of IONOSPHERE_CUSTOM_KEEP_TRAINING_TIMESERIES_FOR and
IONOSPHERE_HISTORICAL_DATA_FOLDER
- Ammend ionosphere to add historical training data to the ionosphere.training_data
Redis set
- Handle historical training data in the webapp
Modified:
skyline/features_profile.py
skyline/ionosphere/agent.py
skyline/webapp/templates/training_data.html

IONOSPHERE_CUSTOM_KEEP_TRAINING_TIMESERIES_FOR

---

skyline/analyzer/algorithms_batch.py
skyline/analyzer/analyzer_batch.py
skyline/mirage/mirage.py
skyline/settings.py

IssueID #3684: ROOMBA_BATCH_METRICS_CUSTOM_DURATIONS
IssueID #3650: ROOMBA_DO_NOT_PROCESS_BATCH_METRICS
- Added ROOMBA_BATCH_METRICS_CUSTOM_DURATIONS to settings and analyzer_batch (3684)
- Allow for custom durations on namespaces, this is for testing to allow the
Redis key to have data at a different resolution than FULL_DURATION, which
allows for feeding a metric at 1 data point per 10 mins (ala fake Mirage) (3684)
IssueID #3678:  SNAB - anomalyScore
- Added SNAB_DATA_DIR and SNAB_anomalyScore to settings and analyzer_batch to
allow for the recording of anomalyScore
Modified:

SNAB - anomalyScore and ROOMBA_BATCH_METRICS_CUSTOM_DURATIONS

---

docs/flux.rst
skyline/flux/listen.py
skyline/flux/worker.py
skyline/settings.py

IssueID #3694: flux - POST multiple metrics
- Added the ability to POST multiple metrics in a single request
- FLUX_API_KEYS to settings
- Added the validation of key against FLUX_API_KEYS or FLUX_SELF_API_KEY for
flux requests
- Handle Redis and literal_eval separately in worker
Modified:
docs/flux.rst

flux - POST multiple metrics

---

skyline/analyzer/analyzer.py
skyline/flux/worker.py
skyline/settings.py

IssueID #3708: FLUX_ZERO_FILL_NAMESPACES
- Added FLUX_ZERO_FILL_NAMESPACES to settings
- Create the flux.zero_fill_metrics Redis set in analyzer
- In flux worker send 0 if metric in the flux.zero_fill_metrics Redis set has
not submitted data in the last 60 seconds.
Modified:

FLUX_ZERO_FILL_NAMESPACES

---

skyline/flux/listen.py

IssueID #3718: Allow flux to handle timestamp in the same minute period
- Only invalidate a submission if it is more the timestamp is greater than (now + 60)
into the future.  Allowing for submissions for the same minute period when the
submission is for the end of that minute.
Modified:

Allow flux to handle timestamp in the same minute period

---

skyline/analyzer/analyzer.py
skyline/settings.py

IssueID #3730: Validate Mirage running multiple processes
- Added MIRAGE_PROCESSES to settings
- Add mirage check files immediately if possible rather than waiting to add all
in the alerting phase.  This is done to reduce the time it takes to get
through the analysis pipeline
- Do not operate on analyzer_batch algorithm error files in analyzer
Modified:

Validate Mirage running multiple processes

---

skyline/webapp/webapp.py

IssueID #3740: webapp - anomaly API endpoint
- always return end_timestamp
Modified:

webapp - anomaly API endpoint

---

skyline/analyzer/analyzer.py
skyline/webapp/webapp.py
updates/sql/v2.1.0.sql

IssueID #3766: Refresh mirage.metrics_expiration_times for batch processing
IssueID #3662: Change mirage.last_check keys to timestamp value
- Refresh the mirage.metrics_expiration_times Redis set in Analyzer, this is an
idempotent change as the set is also managed in Mirage but only on metric name
so if the expiry changes it is handled in Analyzer.
Modified:

Refresh mirage.metrics_expiration_times for batch processing

---

skyline/flux/listen.py
skyline/settings.py

IssueID #3764: flux validate metric name
- Validate the metric name in listen
- Added FLUX_GRAPHITE_WHISPER_PATH to setting as it is required by flux to
determine that a metric name and the path does not exceed the maximum maximum
path of length of 4096 characters
Modified:

flux validate metric name

---

skyline/analyzer/analyzer.py

- No longer using added_to_waterfall_timestamp in the analyzer.mirage_check_sent
Redis key
Modified:

No longer using added_to_waterfall_timestamp

---

skyline/custom_algorithms.py

- Change exceed max_execution_time from error to warning and correct formating
Modified:
skyline/custom_algorithms.py
skyline/custom_algorithms/last_same_hours.py

Change exceed max_execution_time from error to warning

---

skyline/analyzer/alerters.py
skyline/analyzer/analyzer.py
skyline/analyzer/analyzer_batch.py
skyline/mirage/mirage.py

IssueID #3776: waterfall_alert - no analyzer triggered_algorithms in waterfall_panorama_data on MIRAGE_ALWAYS_METRICS
- Handle getting the anomaly_id in an Analyzer waterfall alert for an http_alerter
- Added triggered_algorithms and algorithms_run to the anomalous_metric list
- Do not waterfall alert in Analyzer on MIRAGE_ALWAYS_METRICS that have
triggered_algorithms < CONSENSUS
- Do not modify the alert list object for waterfall and snab alerts create a
new_alert list
Modified:

Handle anomaly_id in a Analyzer waterfall alert

---

skyline/analyzer/analyzer.py
skyline/crucible/crucible.py
skyline/flux/populate_metric_worker.py
skyline/mirage/mirage.py
skyline/skyline_functions.py
skyline/vista/fetcher.py

IssueID #3780: skyline_functions - sanitise_graphite_url
IssueID #3776: waterfall_alert - no analyzer triggered_algorithms in waterfall_panorama_data on MIRAGE_ALWAYS_METRICS
- Added sanitise_graphite_url function to skyline_functions to handle double
encoding of forward slashes in metric names from %2F to %252F on requests made
to Graphite
- Corrected datapoint, timestamp order in MIRAGE_ALWAYS_METRICS waterfall_data
Modified:
skyline/vista/fetcher.py

skyline_functions - sanitise_graphite_url

---

skyline/ionosphere/ionosphere.py

IssueID #3782: Exclude disabled echo features profile
- Remove disabled echo features profiles from evaluation
Modified:

Exclude disabled echo features profile

---

skyline/analyzer/alerters.py
skyline/mirage/mirage_alerters.py

- Do not alert to external http_alert with no anomaly_id, handle edge cases
where no anomaly_id is present
Modified:

Do not alert to external http_alert with no anomaly_id

---

skyline/algorithm_exceptions.py
skyline/analyzer/algorithms.py

IssueID #3792: algorithm_exceptions - EmptyTimeseries
- Added EmptyTimeseries to identify and removes from unique_metrics set as soon
as possible for efficiency
Modified:
skyline/algorithm_exceptions.py

algorithm_exceptions - EmptyTimeseries

---

skyline/analyzer/analyzer.py
skyline/analyzer/analyzer_batch.py

IssueID 3652: Handle multiple metrics in base_name conversion
IssueID 3734: waterfall alerts
IssueID 3766: Refresh mirage.metrics_expiration_times for batch processing
IssueID 3788: snab_flux_load_test
IssueID 3800: Handle feedback metrics in Mirage and waterfall alerts
IssueID 3808: ANALYZER_DYNAMICALLY_ANALYZE_LOW_PRIORITY_METRICS
IssueID 3810: ANALYZER_MAD_LOW_PRIORITY_METRICS
IssueID 3812: ANALYZER_ANALYZE_LOW_PRIORITY_METRICS
IssueID #3818: ANALYZER_BATCH_PROCESSING_OVERFLOW_ENABLED
- Allow anayzer_batch to iterate and process multiple metrics per run for
efficiency in only build common lists once.
- All the features in the referenced issues
Modified:

analyzer and analyzer_batch changes

---

docs/analyzer.rst
docs/flux.rst
skyline/flux/flux.py
skyline/flux/listen.py
skyline/flux/populate_metric_worker.py
skyline/flux/worker.py
skyline/skyline_functions.py

IssueID #3798: FLUX_PERSIST_QUEUE
IssueID #3788: snab_flux_load_test
IssueID #3764: flux validate metric name
IssueID #3780: skyline_functions - sanitise_graphite_url
IssueID #3790: flux - pickle to Graphite
IssueID #3796: FLUX_CHECK_LAST_TIMESTAMP
- Allow flux to persist the queue in the flux.queue Redis set
- Added FLUX_VERBOSE_LOGGING to allow for disabling request and data logging
- flux validate metric name
- Use encode_graphite_metric_name function
- Change flux worker to pickle data to Graphite
- Allow the disabling of the use to the flux.last Redis keys with the added
setting of FLUX_CHECK_LAST_TIMESTAMP
- Update docs
Modified:
docs/flux.rst …

flux changes

---

bin/snab_flux_load_test.d
docs/SNAB.rst
skyline/snab/snab_flux_load_test.py
skyline/snab/snab_flux_load_test_agent.py
utils/dawn/skyline.dawn.sh

IssueID #3788: snab_flux_load_test
- Added snab_flux_load_test
- Updated SNAB doc
- Updated skyline.dawn.sh to SNAB branch and mitigated Graphite setuptools issue
as per https://github.com/graphite-project/graphite-web/issues/2566
Added:
bin/snab_flux_load_test.d
skyline/snab/snab_flux_load_test.py
skyline/snab/snab_flux_load_test_agent.py
Modified:
docs/SNAB.rst

snab_flux_load_test

---

docs/horizon.rst
docs/running-multiple-skylines.rst
skyline/horizon/agent.py
skyline/horizon/worker.py
skyline/settings.py

- Allow horizon to only submit metrics to Redis if they are assigned to the
horizon shard.
Modified:
docs/horizon.rst
skyline/horizon/agent.py

HORIZON_SHARDS

---

skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #3770: webapp - analyzer_last_status API endoint
- Added api method to return the Redis analyzer key data
Modified:

webapp - analyzer_last_status API endoint

---

skyline/skyline.sql
updates/sql/v2.1.0-patch-dev-3828.sql
updates/sql/v2.1.0.sql

IssueID #3828: Add inactive columns to the metrics DB table
- Added inactive and inactive_at columns to the metrics table
- Added inactive and ionosphere_enabled to the metric index
Added:
updates/sql/v2.1.0-patch-dev-3828.sql
Modified:
updates/sql/v2.1.0.sql

Add inactive columns to the metrics DB table

---

skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #3368: webapp api - ionosphere_learn_work
- Convert strings to json and request parameter format=json to return a pure
json response
Modified:

webapp api - ionosphere_learn_work - add pure json response

---

skyline/analyzer/agent.py
skyline/analyzer/analyzer.py
skyline/analyzer/metrics_manager.py
skyline/external_alert_configs.py
skyline/mirage/mirage.py

IssueID #3830: metrics_manager
- Add a dedicated process that is controlled by analyzer/agent.py to manage
lists, Redis sets and hash keys related to metrics and alerting classification
outside and independently of the analysis process/es.
Added:
Modified:
skyline/analyzer/agent.py
skyline/external_alert_configs.py

metrics_manager

---

skyline/analyzer/analyzer.py
skyline/analyzer/metrics_manager.py

IssueID #3830: metrics_manager
IssueID #3808: ANALYZER_DYNAMICALLY_ANALYZE_LOW_PRIORITY_METRICS
- Use the metrics_manager mirage.hash_key.metrics_resolutions for Mirage metric
resolutions rather that the individual mirage.metrics. Redis keys (3830)
- Disabled a number of functions in analyzer that are now run in metrics_manager
via the if not ANALYZER_USE_METRICS_MANAGER conditional (3830)
- Changed metrics_manager from running every 60 seconds to 300 seconds (3830)
- Manage derivative metrics more efficiently and fix bug introduced for batch
processing that results in the z.derivative_metric keys not being refreshed as
it was setevery run if it existed.  Now only …

misc analyzer and metrics_manager changes

---

skyline/mirage/mirage.py
skyline/mirage/mirage_alerters.py

- Add the real anomalyScore to the http alert
Modified:

Add the real anomalyScore to the http alert

---

docs/panorama.rst
docs/running-multiple-skylines.rst
skyline/settings.py
skyline/webapp/backend.py
skyline/webapp/gunicorn.py
skyline/webapp/webapp.py

- Added the get_cluster_data function to enable api requests to get data from
the /api of REMOTE_SKYLINE_INSTANCES.  This allows the user to query a single
Skyline webapp node in a cluster and the Skyline instance will respond with
the concentated responses of all the REMOTE_SKYLINE_INSTANCES in one a single
response.
- Added the cluster_data argument to api methods that can require data from the
cluster in the response
- Changed default rebrow page from Server to Keys
- Added WEBAPP_GUNICORN_WORKERS and WEBAPP_GUNICORN_BACKLOG to settings and in
gunicorn.py
- Updated docs on cluster aspects
Modified:
docs/panorama.rst
skyline/webapp/gunicorn.py …

get_cluster_data - wip

---

skyline/analyzer/alerters.py
skyline/analyzer/analyzer.py
skyline/mirage/mirage_alerters.py

- Add the 3sigma_upper, 3sigma_lower and 3sigma_lower_real bounds to the http
alert
- Determine triggered_algorithms and alogrithms_run in analyzer to determine the
real anomalyScore from to pass to the http alert
Modified:

Add the upper and lower 3sigma bounds to the http alert

---

skyline/analyzer/analyzer.py

- With manage_derivative_metrics running every 300  seconds the metric has to be
monotonic in the last 15 data pointsWith manage_derivative_metrics running
every 300 seconds the metric has to be monotonic in the last 15 data points
Modified:

Set monotonic_count to 3

---

skyline/analyzer/alerters.py
skyline/analyzer/analyzer.py
skyline/mirage/mirage_alerters.py

- Allow time for the alerter to add the upper and lower 3sigma bounds from the
training data before removing
- Add the upper and lower 3sigma bounds only if the metric is a
smtp_alerter_metrics metric, if not, there will be no training data
Modified:

Only calculate 3sigma bounds if smtp_alerter_metrics metric

---

skyline/ionosphere/layers.py
skyline/luminosity/process_correlations.py
skyline/webapp/backend.py
skyline/webapp/webapp.py

IssueID #2464: luminosity_remote_data
IssueID #2558: Ionosphere - fluid approximation - approximately_close on layers
IssueID #3756: LUMINOSITY_CORRELATION_MAPS
- Convert metric_name bytes to str in backend.py and wrapped luminosity_remote_data
in try and added more logging to webapp.py (3824, 2464, 3266, 3262)
- Correct sign of e_boundary_limit where e_condition == '<' or '<=' (2558)
- Added LUMINOSITY_CORRELATION_MAPS - WIP to process_correlations.py (3756) and
use correct url with api for get_cluster_data (3756)
Modified:
skyline/ionosphere/layers.py

get_cluster_data handle in luminosity_remote_data

---

skyline/webapp/ionosphere_backend.py

IssueID #3844: Handle no features profile in webapp
- Handle no features profile in webapp, convert bad SQL to select where metric
id=0
Modified:

Handle no features profile in webapp

---

docs/alerts.rst
docs/algorithms/custom-algorithms.rst
skyline/custom_algorithms_to_run.py
skyline/horizon/worker.py
skyline/mirage/mirage_algorithms.py
skyline/settings.py
skyline/webapp/templates/crucible_process_metrics.html

IssueID #3848: custom_algorithms - run_before_3sigma parameter
- Added the run_before_3sigma and run_only_if_consensus parameters to
custom_algorithms (mirage only)
- A custom_algorithm can now be run after three-sigma algorithms only if they
reach CONSENSUS
- Tidied up some docs and typos
Modified:
docs/alerts.rst
skyline/custom_algorithms_to_run.py
skyline/webapp/templates/crucible_process_metrics.html

custom_algorithms - run_before_3sigma parameter

---

skyline/webapp/backend.py
skyline/webapp/webapp.py

- set cannot be used on all training_data as each item includes a list which is
unhashable
- typo in log string
Modified:

get_cluster_data fixes

---

skyline/analyzer/alerters.py
skyline/analyzer/analyzer.py
skyline/boundary/boundary_alerters.py
skyline/mirage/mirage_alerters.py
skyline/webapp/webapp.py

- Added origin host and shard to slack and http_alert status if the alert comes
from a cluster server
Modified:

Add origin and shard to alerts

---

skyline/analyzer/alerters.py
skyline/boundary/boundary_alerters.py
skyline/mirage/mirage_alerters.py
skyline/webapp/backend.py
skyline/webapp/webapp.py

- Correct shard type to slack and http_alert
- Added cluster_data element to response status
- Determine which remote Skyline host the metric is assigned to and return the
client a redirect to the remote Skyline instance that will have the ionosphere
training data for the metric
Modified:

HORIZON_SHARDS and get_cluster_data related changes

---

skyline/ionosphere/ionosphere.py

- If the check just done is newer than an existing mirage waterfall alert metric
timestamp remove those keys as well
Modified:

Remove older waterfall_alerts

---

skyline/webapp/backend.py
skyline/webapp/templates/api.html

IssueID #3850: webapp - yhat_values API endoint
- Set the yhat_real_lower correctly
- Add API method documentation
Modified:

webapp - yhat_values API endoint

---

skyline/analyzer/analyzer.py

IssueID #3856: Handle boring sparsely populated metrics in derivative_metrics
- Do not log error if zz.derivative_metric.last_timestamp. Redis key does not
exist, only set to int if the response in not None otherwise it will log an
error and if this data does not exist it is OK it is idempotent
Modified:

Handle boring sparsely populated metrics in derivative_metrics

---

skyline/webapp/webapp.py

- Do not use set on unhashable list for remote_training_data
Modified:

get_cluster_data

---

skyline/luminosity/process_correlations.py
skyline/settings.py
skyline/skyline_functions.py
skyline/webapp/backend.py
skyline/webapp/webapp.py

IssueID #3860: luminosity - handle low frequency data
- Enable luminosity to dynamically handle varying metric resolutions and data
that is of a lower frequency than 60 seconds automatically using the
resolution of the data (best effort) to determine the offsets to use for cross
correlation aanalysis.  This requires a change in process_correlations and to
the /api?luminosity_remote_data functions in webapp and the backend to allow
the resolution to be passed.
Modified:
IssueID #3858: skyline_functions - correlate_or_relate_with
IssueID #3740: webapp - anomaly API endpoint
- Added correlate_or_relate_with to skyline_functions
- Use correlate_or_relate_with in webapp /api?anomaly endpoint to filter …

luminosity - handle low frequency data and

---

skyline/webapp/webapp.py

IssueID #3368: webapp api - ionosphere_learn_work
- Return an array of work, json cannot be keyed on metric name as a metric could
have multiple work items
Modified:

webapp api - ionosphere_learn_work

---

docs/analyzer.rst
docs/installation.rst
skyline/analyzer/analyzer.py
skyline/analyzer/metrics_manager.py
skyline/settings.py

IssueID #3870: metrics_manager - check_data_sparsity
- Add the ability for metrics_manager to determine how fully populated metric
timeseries are and send metrics metrics_sparsity metrics to Graphite
- Added the CHECK_DATA_SPARSITY and SKIP_CHECK_DATA_SPARSITY_NAMESPACES
variables to settings.
- Updated the Analyzer documentation page
Modified:

metrics_manager - check_data_sparsity

---

skyline/flux/listen.py
skyline/flux/worker.py

IssueID #3694: flux - POST multiple metrics
IssueID #3864: flux - try except everything
- Added metric count in listen.py on POST with mutliple metrics
-
Modified:

misc flux logging changes

---

dev-requirements.txt
requirements.txt

IssueID #3694: #3874: SNYK-PYTHON-PY-1049546
Dependency vulnerability - py - CVE-2020-29651 #378
- Update py to 1.10.0 which resolves CVE-2020-29651 by implementing
https://github.com/pytest-dev/py/pull/257 which fixes
https://github.com/pytest-dev/py/issues/256
Modified:

py 1.10.0 with CVE-2020-29651 mitigated

---

skyline/matched_or_regexed_in_list.py
skyline/webapp/templates/match_metric.html
skyline/webapp/templates/utilities.html
skyline/webapp/webapp.py

IssueID #3880: webapp - utilities - match_metric
- Added page to utilities to submit and metric name and test against a settings
list or a provided string.  Possible issue with encoding in the use of a regex
string.
- Append all URI key values to the training page redirect
- Added ability to pass a custom redirect URL, even badly if required
Added:
skyline/webapp/templates/match_metric.html
Modified:
skyline/matched_or_regexed_in_list.py
skyline/webapp/templates/utilities.html

webapp - utilities - match_metric

---

docs/running-multiple-skylines.rst
skyline/analyzer/analyzer.py
skyline/analyzer/metrics_manager.py
skyline/settings.py
skyline/webapp/ionosphere_backend.py
skyline/webapp/webapp.py

IssueID #3884: ANALYZER_CHECK_LAST_TIMESTAMP
IssueID #3890: metrics_manager - sync_cluster_files
- Added the ability to set Analyzer to only analyze a metric if it has a new
timestamp (or is stale) via the settings ANALYZER_CHECK_LAST_TIMESTAMP
- Added the ability for metrics_manager and the webapp to allow for the
syncing of Ionosphere data between cluster nodes via the SNYC_CLUSTER_FILES
setting.
Modified:

ANALYZER_CHECK_LAST_TIMESTAMP and metrics_manager - sync_cluster_files

---

skyline/analyzer/metrics_manager.py
skyline/boundary/boundary.py

IssueID #3870: metrics_manager - check_data_sparsity
IssueID #3878: Add metric_trigger and alert_threshold to Boundary alerts
- The last 30 measures for uploaded data to flux seemed sufficient, however from
higher frequency real time metrics there is more variance, so using a larger
sample, changed from 30 to 100 and handle slight variances. (3870)
- Send times_seen not alert_threshold to syslog (3878)
Modified:

mics changes metrics_manager and boundary

---

docs/running-multiple-skylines.rst
skyline/analyzer/metrics_manager.py
skyline/settings.py
skyline/webapp/webapp.py

IssueID #3890: metrics_manager - sync_cluster_files
IssueID #3870: metrics_manager - check_data_sparsity
- Handle if roomba has not pruned some data in minutes (3870)
- Remove the entry from the ionosphere.training data Redis set if the directory
does not exist on this node in webapp (3890)
- Correct SNYC_CLUSTER_FILES to SYNC_CLUSTER_FILES (3890)
- Add some caching and use sefl functions (3890)
Modified:

Corrections and improvements to sync_cluster_files

---

skyline/luminosity/luminosity.py
skyline/luminosity/process_correlations.py

- Allow for longer cluster responses with large metric populations
Modified:
skyline/luminosity/luminosity.py

luminosity - Allow for longer cluster responses

---

dev-requirements.txt
docs/tsfresh.rst
requirements.txt
skyline/features_profile.py
skyline/ionosphere/common_functions.py
skyline/ionosphere/ionosphere.py
skyline/tsfresh_feature_names.py
tests/baseline/tsfresh-0.10.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.11.3.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.13.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.14.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.15.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.16.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.17.9.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.6.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.7.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.8.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.9.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh_features_test.py
utils/test_ionosphere_echo.py

IssueID #3928: Update Skyline to use new tsfresh feature extraction method
IssueID #3898: Test Python 3.8.6 and deps
- Update all ionosphere functions to use the new tsfresh feature extraction method
- Update requirements to use earthgecko/tsfresh
- Added tsfresh baseline test data sets
- Update deps
- Update docs
Added:
tests/baseline/tsfresh-0.10.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.11.3.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.13.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.14.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.15.2.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.16.1.py3.data.json.features.transposed.csv
tests/baseline/tsfresh-0.17.9.py3.data.json.features.transposed.csv …

new tsfresh and feature extraction method

---

docs/analyzer.rst
docs/panorama.rst
docs/running-multiple-skylines.rst
skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/features_profiles_matches.html
skyline/webapp/templates/ionosphere.html
skyline/webapp/templates/ionosphere_performance.html
skyline/webapp/templates/search_features_profiles.html
skyline/webapp/templates/validate_features_profiles.html
skyline/webapp/webapp.py
utils/continuity.py

IssueID #3934: ionosphere_performance
IssueID #3850: webapp - yhat_values API endpoint
IssueID #3936: Allow for FLUX_API_KEYS rotation
- Added an ionosphere_performance page and functions to webapp to analyse,
visualise and report on the performance of ionosphere on metrics and namespaces
- Change webapp yhat_values API endpoint to return 204 on no data instead of 404 (3850)
- Allow for key and namespace mapped FLUX_API_KEYS so as to allow a namespace to
have multiple keys which allows for key rotation
- Update docs
- misc docs corrections, modifications and bandit additions
Added:
skyline/webapp/templates/ionosphere_performance.html
Modified:
docs/panorama.rst …

ionosphere_performance

---

dev-requirements.txt
requirements.txt

IssueID #3944: xlrd-2.0.1 removed support for xlsx format
- Update requirements to use xlrd-1.2.0 again
Modified:

Downgrade xlrd

---

docs/upload-data-to-flux.rst
skyline/flux/populate_metric_worker.py
skyline/snab/snab_flux_load_test.py

IssueID #3864: flux - try except everything
- Bring into line with flux worker performance changes, tune flux
populate_metric_worker like flux upload_data in terms of pickle limits
- Added bandit nosec on random.random()
Modified:
skyline/snab/snab_flux_load_test.py

Tune flux populate_metric_worker

---

skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/ionosphere_performance.html

IssueID #3934: ionosphere_performance
- Use the datetime string not the unix timestamp
- Add timezone parameter to post
Modified:
skyline/webapp/templates/ionosphere_performance.html

Fix timezone issue in ionosphere_performance

---

skyline/flux/listen.py
skyline/webapp/ionosphere_backend.py
skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #3968: webapp - last_analyzed_timestamp API endpoint
IssueID #1448: Crucible web UI
IssueID #3934: ionosphere_performance
- Add an API endpoint to the webapp that returns the last_analyzed_timestamp for
a metric from the analyzer.metrics.last_analyzed_timestamp or the
analyzer.low_priority_metrics.last_analyzed_timestamp Redis hash keys.
- Added crucible_jobs_dir to IONOSPHERE_IMAGE_ALLOWED_PATHS
- Correct flux validate_timestamp caller parameter
- Set default start_timestamp and end_timestamp in for ionosphere_performance
Modified:

webapp - last_analyzed_timestamp API endpoint

---

dev-requirements.txt
requirements.txt

IssueID #3972: SNYK-PYTHON-PILLOW-1080635
IssueID #3974: SNYK-PYTHON-AIOHTTP-1079232
- Update to Pillow 8.1.1 as per:
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1080635
CVE-2021-25293 - https://github.com/python-pillow/Pillow/commit/4853e522bddbec66022c0915b9a56255d0188bf9
CVE-2021-25291 - https://github.com/python-pillow/Pillow/commit/8b8076bdcb3815be0ef0d279651d8d1342b8ea61
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1080654
CVE-2021-25292 - https://github.com/python-pillow/Pillow/commit/3bce145966374dd39ce58a6fc0083f8d1890719c
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1081494 (CVE-2021-27921)
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1081501 (CVE-2021-27923)
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1081502 (CVE-2021-27922)
https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1082329 (CVE-2021-25289) …

Update Pillow and aiohttp

---

skyline/skyline.sql
updates/sql/v2.1.0-patch-dev-3978-3642.sql

- Remove id as PRIMARY_KEY from anomalies_type table
Modified:
updates/sql/v2.1.0-patch-dev-3978-3642.sql

anomaly classifications

---

docs/installation.rst
utils/dawn/skyline.dawn.sh
utils/seed_data.py

[Q] The "horizon.test.pickle" test is getting an error. #419
- Add additional output and info informing the user that seed_data will most
likely fail if carbon-relay is already pickling to Horizon
- Move seed_data.py run to before Graphite install.
Modified:
utils/seed_data.py

Add additional info about seed_data and carbon-relay #419

---

skyline/ionosphere/ionosphere.py

- Exclude adtk resources from determining training_data
Modified:

Exclude adtk resources

---

docs/flux.rst
skyline/analyzer/metrics_manager.py
skyline/flux/aggregator.py
skyline/flux/flux.py
skyline/flux/gunicorn.py
skyline/flux/listen.py
skyline/flux/uploaded_data_worker.py
skyline/flux/worker.py
skyline/settings.py

IssueID #4004: flux - aggregator.py and FLUX_AGGREGATE_NAMESPACES
IssueID #3994: Panorama - mirage not anomalous
IssueID #4002: Change flux FLUX_ZERO_FILL_NAMESPACES to pickle
- Added flux/aggregator.py (4004)
- Better handle multiple workers with the introduction of primary_worker, etc
roles (4004)
- Added FLUX_LAST_KNOWN_VALUE_NAMESPACES and FLUX_AGGREGATE_NAMESPACES to
settings.py (4004)
- Changes and corrections to FLUX_ZERO_FILL_NAMESPACES in worker.py (#4002)
- metrics_manager changes to manage the flux aggregator Redis resources (3994)
- metrics_manager changes to manage the mirage.panorama.not_anomalous_metrics
Redis hash (3994)
Added:
skyline/flux/aggregator.py
Modified:
docs/flux.rst
skyline/flux/gunicorn.py …

flux - aggregator.py and FLUX_AGGREGATE_NAMESPACES

---

skyline/analyzer/analyzer_batch.py
skyline/functions/redis/get_metric_timeseries.py
skyline/ionosphere/learn.py
skyline/skyline_functions.py
skyline/webapp/backend.py

IssueID #4280: aet.metrics_manager.derivative_metrics Redis hash
- Change from using derivative_metrics Redis key to
aet.metrics_manager.derivative_metrics
- https://github.com/earthgecko/skyline/pull/445
Modified:
skyline/functions/redis/get_metric_timeseries.py

aet.metrics_manager.derivative_metrics Redis hash

---

skyline/flux/worker.py

IssueID #4060: skyline.flux.worker.discarded metrics
- Send to the Graphite that collects skyline metrics not via flux queue which
could send to a different Graphite
- https://github.com/earthgecko/skyline/pull/453
Modified:

flux - skyline.flux.worker.discarded metrics

---

skyline/settings.py
skyline/validate_settings.py

IssueID #4328: BATCH_METRICS_CUSTOM_FULL_DURATIONS
- New BATCH_METRICS_CUSTOM_FULL_DURATIONS setting
Modified:
skyline/validate_settings.py

BATCH_METRICS_CUSTOM_FULL_DURATIONS setting

---

docs/getting-data-into-skyline.rst

Issue #470
- Thanks to @krishh-konar for identifying that the port documented is not the
default carbon-cache port
Modified:
docs/getting-data-into-skyline.rst

Correct default carbon-cache port

---

skyline/analyzer/algorithms_batch.py
skyline/analyzer/analyzer.py
skyline/external_alert_configs.py
skyline/horizon/roomba.py
skyline/mirage/mirage_algorithms.py

IssueID #4328: BATCH_METRICS_CUSTOM_FULL_DURATIONS
- In algorithms_batch.py and mirage_algorithms.py
Handle BATCH_METRICS_CUSTOM_FULL_DURATIONS,
Calculate the equivalent of the last hour and handle daily frequency data,
Added option to run_before_3sigma for custom_algorithms,
If custom_algorithms were run and did not trigger reset the consensus,
- In analyzer.py
Determine batch_metrics_list from Redis aet.analyzer.batch_processing_metrics set,
Attempt to get resolution from Redis,
Update alert.paused cache_key name interpolation
- Added missing second_order_resolution_hours to external_alert_configs.py
- Ensure that known and new batch_processing_metrics are accounted for in
roomba.py
Modified: …

BATCH_METRICS_CUSTOM_FULL_DURATIONS

---

skyline/analyzer/metrics_manager.py
skyline/functions/redis/update_set.py
skyline/thunder/thunder.py

IssueID #4364: Prune old thunder.events
IssueID #1444: thunder
- Prune old thunder.events
- Fix log logic in redis/update_set.py
Modified:
skyline/functions/redis/update_set.py
skyline/thunder/thunder.py

Manage thunder.events

---

skyline/analyzer/algorithms.py
skyline/analyzer/algorithms_batch.py
skyline/analyzer/analyzer_batch.py

IssueID #4328: BATCH_METRICS_CUSTOM_FULL_DURATIONS
- With the addition of the custom_consensus_override and the possibility
of the ensemble list being filled with None value when TooShort, etc
handle if the ensemble list is all None and do not return anomalous as True
- Prune any analyzer_batch data with custom_duration to its custom duration
Modified:

Handle if the ensemble list is all None

---

skyline/boundary/boundary_alerters.py

IssueID #4366: Fix boundary slack channels match
- Handle mutliple channels in tuple and de-duplicate channels list
Modified:

Fix boundary slack channels match

---

skyline/functions/settings/get_custom_stale_period.py
skyline/functions/thunder/stale_metrics.py

- Rename custom_stale_period to custom_stale_period_int
- Correct list from external_parent_namespaces to
external_parent_namespaces_stale_periods
Modified:
skyline/functions/settings/get_custom_stale_period.py
skyline/functions/thunder/stale_metrics.py

IssueID #4076: CUSTOM_STALE_PERIOD

---

skyline/boundary/boundary_alerters.py

- Check namespace elements as well
Modified:

IssueID #4366: Fix boundary slack channels match

---

skyline/analyzer/metrics_manager.py
skyline/flux/aggregator.py
skyline/flux/listen.py
skyline/functions/flux/reload_flux.py
skyline/functions/settings/external_settings_aggregation.py
skyline/functions/settings/get_external_settings.py
skyline/functions/thunder/no_data.py
skyline/settings.py
skyline/webapp/templates/api.html
skyline/webapp/webapp.py

IssueID #4404: flux - external_settings - aggregation
IssueID #4324: flux - reload external_settings
IssueID #4376: webapp - update_external_settings
- Determine flux namespace quotas in metrics_manager with
metrics_manager.flux.namespace_quotas hash (#4400)
- Handle external_settings_aggregations settings from EXTERNAL_SETTINGS in
metrics_manager with metrics_manager.flux.aggregate_namespaces hash (#4404)
- Move flux_reload from webapp to metrics_manager using
skyline.external_settings.update.metrics_manager key
- In flux aggregator if method_suffix is not set but multiple methods are being
used, method_suffix must be applied, otherwise the metric will have all the
method values submitted to a single metric name (#4400)
- Handle quota and aggregation in flux listen (#4400, #4404)
- …

IssueID #4400: flux - quota

---

skyline/analyzer/agent.py
skyline/analyzer/agent_batch.py
skyline/boundary/agent.py
skyline/crucible/agent.py
skyline/flux/logger.py
skyline/horizon/agent.py
skyline/ionosphere/agent.py
skyline/luminosity/agent.py
skyline/mirage/agent.py
skyline/panorama/agent.py
skyline/snab/agent.py
skyline/snab/snab_flux_load_test_agent.py
skyline/thunder/agent.py
skyline/vista/agent.py

IssueID #4018: thunder - skyline.errors
- Added RedisErrorLogHandler to add agents
Modified:
skyline/analyzer/agent.py
skyline/analyzer/agent_batch.py
skyline/boundary/agent.py
skyline/crucible/agent.py
skyline/flux/logger.py
skyline/horizon/agent.py
skyline/ionosphere/agent.py
skyline/luminosity/agent.py
skyline/mirage/agent.py
skyline/panorama/agent.py
skyline/snab/agent.py
skyline/snab/snab_flux_load_test_agent.py
skyline/thunder/agent.py
skyline/vista/agent.py

Add RedisErrorLogHandler to agents

---

skyline/functions/metrics_manager/get_flux_namespaces.py
skyline/luminosity/cloudburst.py
skyline/luminosity/cloudbursts.py

IssueID #4552: v3.0.3
IssueID #4536: Handle Redis failure
- Change error to warning for Graphite timeseries is unavailable (4164: luminosity - cloudbursts)
- Added missing log str (#4536: Handle Redis failure)
Modified:
skyline/functions/metrics_manager/get_flux_namespaces.py
skyline/luminosity/cloudburst.py
skyline/luminosity/cloudbursts.py

v3.0.3 (2)

---

docs/readthedocs.requirements.txt

IssueID #4974: v4.0.0
- More readthedocs build malarkey with Sphinx. Not Sphinx==7.0.1 because sphinx-rtd-theme 1.2.2 depends on sphinx<7 and >=1.6 so use Sphinx==6.2.1
Modified:
docs/readthedocs.requirements.txt

IssueID #4962: Build and test skyline v4.0.0
